In [1]:
from pathlib import Path
from table2text.evaluation import (
    init_notebook_evaluation,
    prepare_examples_for_notebook,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
    diagnostics_for_notebook,
    aggregate_for_notebook,
)

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")

KeyboardInterrupt:

In [ ]:
paths = init_notebook_evaluation(project_dir)
paths

{'dataset_config': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/config/datasets.json'),
 'variant_config': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/config/variants.json'),
 'metric_config': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/config/metrics.json'),
 'prepared_examples': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/prepared/all_examples.jsonl'),
 'generations': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/generations.jsonl'),
 'run_root': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/runs'),
 'reference_metrics': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/reference_metrics.jsonl'),
 'deepeval_metrics': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/deepeval_metrics.jsonl'),
 'diagnostics': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/diagnostics.csv'),
 'analysis': PosixPath('/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/analysis')}

In [ ]:
prep = prepare_examples_for_notebook(
    project_dir,
    skip_unavailable=True,
)
prep

Generating train split: 100%|██████████| 3690/3690 [00:00<00:00, 15164.59 examples/s]
Generating test split: 100%|██████████| 1230/1230 [00:00<00:00, 23137.30 examples/s]
Generating validation split: 100%|██████████| 1230/1230 [00:00<00:00, 9003.21 examples/s]
Generating train split: 100%|██████████| 121153/121153 [00:01<00:00, 103567.27 examples/s]
Generating validation split: 100%|██████████| 7700/7700 [00:00<00:00, 100037.61 examples/s]
Generating test split: 100%|██████████| 7700/7700 [00:00<00:00, 99667.14 examples/s]
Generating challenge_train_sample split: 100%|██████████| 500/500 [00:00<00:00, 55617.05 examples/s]
Generating challenge_validation_sample split: 100%|██████████| 500/500 [00:00<00:00, 44997.47 examples/s]
Downloading data: 11.1MB [00:00, 103MB/s]
Downloading data: 100%|██████████| 881k/881k [00:00<00:00, 9.85MB/s]
Downloading data: 100%|██████████| 1.08M/1.08M [00:00<00:00, 30.9MB/s]
Downloading data: 100%|██████████| 70.6k/70.6k [00:00<00:00, 1.47MB/s]
Generating train split: 100%|██████████| 33525/33525 [00:00<00:00, 76809.40 examples/s]
Generating validation split: 100%|██████████| 1484/1484 [00:00<00:00, 72296.27 examples/s]
Generating test split: 100%|██████████| 1847/1847 [00:00<00:00, 77967.79 examples/s]
Generating challenge_train_sample split: 100%|██████████| 500/500 [00:00<00:00, 66837.24 examples/s]
Generating challenge_validation_sample split: 100%|██████████| 500/500 [00:00<00:00, 58527.35 examples/s]
Generating challenge_test_scramble split: 100%|██████████| 500/500 [00:00<00:00, 50637.50 examples/s]
Generating train split: 100%|██████████| 35426/35426 [00:00<00:00, 629647.70 examples/s]
Generating validation split: 100%|██████████| 1667/1667 [00:00<00:00, 440324.00 examples/s]
Generating test split: 100%|██████████| 1779/1779 [00:00<00:00, 592430.87 examples/s]
Generating challenge_train_sample split: 100%|██████████| 502/502 [00:00<00:00, 207177.07 examples/s]
Generating challenge_validation_sample split: 100%|██████████| 499/499 [00:00<00:00, 102908.73 examples/s]
Generating challenge_test_scramble split: 100%|██████████| 500/500 [00:00<00:00, 152497.96 examples/s]
Generating challenge_test_numbers split: 100%|██████████| 500/500 [00:00<00:00, 235873.58 examples/s]
Downloading data: 100%|██████████| 23.0M/23.0M [00:00<00:00, 29.3MB/s]
Downloading data: 100%|██████████| 2.47M/2.47M [00:00<00:00, 23.9MB/s]
Downloading data: 100%|██████████| 4.50M/4.50M [00:00<00:00, 41.0MB/s]
Generating train split: 100%|██████████| 62659/62659 [00:01<00:00, 41924.26 examples/s]
Generating validation split: 100%|██████████| 2768/2768 [00:00<00:00, 39876.74 examples/s]
Generating test split: 100%|██████████| 5097/5097 [00:00<00:00, 40140.54 examples/s]
Generating train split: 5103 examples [00:00, 5744.39 examples/s]
Generating validation split: 714 examples [00:00, 45333.53 examples/s]
Generating test split: 1083 examples [00:00, 71821.64 examples/s]
Generating challenge_train_1_percent split: 50 examples [00:00, 18572.02 examples/s]
Generating challenge_train_2_percent split: 103 examples [00:00, 33793.28 examples/s]
Generating challenge_train_5_percent split: 256 examples [00:00, 54524.04 examples/s]
Generating challenge_train_10_percent split: 510 examples [00:00, 66738.27 examples/s]
Generating challenge_train_20_percent split: 1021 examples [00:00, 72918.95 examples/s]
Generating train split: 100%|██████████| 22749/22749 [00:03<00:00, 6999.68 examples/s]
Generating test split: 100%|██████████| 1744/1744 [00:00<00:00, 8012.39 examples/s]
Generating validation split: 100%|██████████| 1739/1739 [00:00<00:00, 8219.04 examples/s]
/Users/realgobs/.cache/huggingface/modules/datasets_modules/datasets/GEM--conversational_weather/62aca275360af46475dbb166c7f18df5ea26c58b38b4874dfb23ee6bd59fe3cd/conversational_weather.py:134: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.config.name is 'challenge':
Downloading data: 100%|██████████| 19.0M/19.0M [00:00<00:00, 30.9MB/s]
Downloading data: 100%|██████████| 2.29M/2.29M [00:00<00:00, 28.8MB/s]
Downloading data: 100%|██████████| 2.37M/2.37M [00:00<00:00, 33.8MB/s]
Generating train split:  37%|███▋      | 9509/25390 [00:00<00:00, 47975.72 examples/s]

/Users/realgobs/.cache/huggingface/datasets/downloads/71e060738bda84635d1585921f01edd2dd059c649e52565911082b959b44d63f

Generating train split: 100%|██████████| 25390/25390 [00:00<00:00, 50916.06 examples/s]
Generating test split: 100%|██████████| 3121/3121 [00:00<00:00, 51456.67 examples/s]

/Users/realgobs/.cache/huggingface/datasets/downloads/9bb973512e0675a045a2bda4849caeff389f4de22017c6f9089c2fc6eaf5b677

Generating validation split: 100%|██████████| 3078/3078 [00:00<00:00, 53302.45 examples/s]

/Users/realgobs/.cache/huggingface/datasets/downloads/2cdc03f82f52cf42becb82801041e2f1f9b646c6fc1deaeec161a538621672ed

Generating train split: 6159 examples [00:00, 16980.12 examples/s]
Generating validation split: 755 examples [00:00, 24751.06 examples/s]
Generating test split: 706 examples [00:00, 24406.99 examples/s]
Generating train split: 100%|██████████| 242/242 [00:00<00:00, 4463.73 examples/s]
Generating test split: 100%|██████████| 241/241 [00:00<00:00, 6479.16 examples/s]
Generating validation split: 100%|██████████| 240/240 [00:00<00:00, 7344.90 examples/s]

,dataset_id,status,requested_split,example_count,output_path,warnings,error
0,sportsett_basketball,scored,test,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
1,totto,scored,validation,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
2,e2e_nlg,scored,test,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
3,web_nlg,scored,test,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
4,dart,scored,test,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
5,logicnlg,scored,test,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
6,fetaqa,scored,test,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
7,viggo,scored,test,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
8,mlb_data_to_text,scored,test,20,/Users/realgobs/Documents/MScproject/table2tex...,[],None
9,conversational_weather,scored,test,30,/Users/realgobs/Documents/MScproject/table2tex...,[],None
10,turku_hockey,scored,test,20,/Users/realgobs/Documents/MScproject/table2tex...,[],None
11,rotowire_english_german,scored,test,20,/Users/realgobs/Documents/MScproject/table2tex...,[],None

In [ ]:
metrics = score_reference_metrics_for_notebook(project_dir)
metrics[["dataset_id", "variant_id", "metric_name", "status", "score"]].head()

KeyError: "None of [Index(['dataset_id', 'variant_id', 'metric_name', 'status', 'score'], dtype='object')] are in the [columns]"

In [ ]:
diagnostics = diagnostics_for_notebook(project_dir)
analysis_paths = aggregate_for_notebook(project_dir)

diagnostics.head(), analysis_paths

EmptyDataError: No columns to parse from file

In [ ]:
%pip install -e "/Users/realgobs/Documents/MScproject/table2text_pydanticai[dev,evaluation]"

Obtaining file:///Users/realgobs/Documents/MScproject/table2text_pydanticai
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: numpy<3.0,>=1.26 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (2.4.6)
Requirement already satisfied: openpyxl<4.0,>=3.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (3.1.5)
Requirement already satisfied: pandas<3.0,>=2.2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (2.3.3)
Requirement already satisfied: pyarrow>=16.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (25.0.0)
Requirement already satisfied: pydantic-ai-slim<2.0,>=1.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (1.107.1)
Requirement already satisfied: pydantic<3.0,>=2.10 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (2.13.4)
Requirement already satisfied: scikit-learn<2.0,>=1.5 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (1.9.0)
Requirement already satisfied: pytest-asyncio<1.0,>=0.24 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (0.26.0)
Requirement already satisfied: pytest<9.0,>=8.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (8.4.2)
Requirement already satisfied: ruff<1.0,>=0.8 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (0.15.21)
Requirement already satisfied: bert-score<0.4,>=0.3.13 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (0.3.13)
Collecting datasets<4.0,>=3.2 (from table2text-pydanticai==0.1.0)
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: huggingface-hub<1.0,>=0.27 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (0.36.2)
Requirement already satisfied: nltk<4.0,>=3.9 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (3.10.0)
Requirement already satisfied: rouge-score<0.2,>=0.1.2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (0.1.2)
Requirement already satisfied: sacrebleu<3.0,>=2.4 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (2.6.0)
Requirement already satisfied: scipy<2.0,>=1.13 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (1.17.1)
Requirement already satisfied: sentencepiece<0.3,>=0.2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (0.2.2)
Requirement already satisfied: tabulate<1.0,>=0.9 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (0.9.0)
Requirement already satisfied: torch<3.0,>=2.3 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (2.13.0)
Requirement already satisfied: transformers<5.0,>=4.46 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from table2text-pydanticai==0.1.0) (4.57.6)
Requirement already satisfied: requests in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (2.34.2)
Requirement already satisfied: tqdm>=4.31.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (4.68.4)
Requirement already satisfied: matplotlib in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (3.11.1)
Requirement already satisfied: packaging>=20.9 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (26.2)
Requirement already satisfied: filelock in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (3.32.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets<4.0,>=3.2->table2text-pydanticai==0.1.0)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: xxhash in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (3.8.1)
Collecting multiprocess<0.70.17 (from datasets<4.0,>=3.2->table2text-pydanticai==0.1.0)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.3.0,>=2023.1.0 (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pyyaml>=5.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (3.14.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.27->table2text-pydanticai==0.1.0) (1.5.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.27->table2text-pydanticai==0.1.0) (4.16.0)
Requirement already satisfied: defusedxml in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from nltk<4.0,>=3.9->table2text-pydanticai==0.1.0) (0.7.1)
Requirement already satisfied: click in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from nltk<4.0,>=3.9->table2text-pydanticai==0.1.0) (8.3.3)
Requirement already satisfied: joblib in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from nltk<4.0,>=3.9->table2text-pydanticai==0.1.0) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from nltk<4.0,>=3.9->table2text-pydanticai==0.1.0) (2026.7.10)
Requirement already satisfied: et-xmlfile in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from openpyxl<4.0,>=3.1->table2text-pydanticai==0.1.0) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pandas<3.0,>=2.2->table2text-pydanticai==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pandas<3.0,>=2.2->table2text-pydanticai==0.1.0) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pandas<3.0,>=2.2->table2text-pydanticai==0.1.0) (2026.3)
Requirement already satisfied: annotated-types>=0.6.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic<3.0,>=2.10->table2text-pydanticai==0.1.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic<3.0,>=2.10->table2text-pydanticai==0.1.0) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic<3.0,>=2.10->table2text-pydanticai==0.1.0) (0.4.2)
Requirement already satisfied: genai-prices>=0.0.62 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (0.0.71)
Requirement already satisfied: griffelib>=2.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (2.1.0)
Requirement already satisfied: httpx>=0.27 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (0.28.1)
Requirement already satisfied: opentelemetry-api>=1.28.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (1.44.0)
Requirement already satisfied: pydantic-graph==1.107.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (1.107.1)
Requirement already satisfied: logfire-api>=3.14.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-graph==1.107.1->pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (4.37.0)
Requirement already satisfied: openai>=2.29.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (2.45.0)
Requirement already satisfied: tiktoken>=0.12.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (0.13.0)
Requirement already satisfied: iniconfig>=1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pytest<9.0,>=8.0->table2text-pydanticai==0.1.0) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pytest<9.0,>=8.0->table2text-pydanticai==0.1.0) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from pytest<9.0,>=8.0->table2text-pydanticai==0.1.0) (2.20.0)
Requirement already satisfied: absl-py in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from rouge-score<0.2,>=0.1.2->table2text-pydanticai==0.1.0) (2.5.0)
Requirement already satisfied: six>=1.14.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from rouge-score<0.2,>=0.1.2->table2text-pydanticai==0.1.0) (1.17.0)
Requirement already satisfied: portalocker in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from sacrebleu<3.0,>=2.4->table2text-pydanticai==0.1.0) (3.2.0)
Requirement already satisfied: colorama in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from sacrebleu<3.0,>=2.4->table2text-pydanticai==0.1.0) (0.4.6)
Requirement already satisfied: lxml in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from sacrebleu<3.0,>=2.4->table2text-pydanticai==0.1.0) (6.1.1)
Requirement already satisfied: narwhals>=2.0.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from scikit-learn<2.0,>=1.5->table2text-pydanticai==0.1.0) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from scikit-learn<2.0,>=1.5->table2text-pydanticai==0.1.0) (3.6.0)
Requirement already satisfied: setuptools>=77.0.3 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from torch<3.0,>=2.3->table2text-pydanticai==0.1.0) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from torch<3.0,>=2.3->table2text-pydanticai==0.1.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from torch<3.0,>=2.3->table2text-pydanticai==0.1.0) (3.6.1)
Requirement already satisfied: jinja2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from torch<3.0,>=2.3->table2text-pydanticai==0.1.0) (3.1.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from transformers<5.0,>=4.46->table2text-pydanticai==0.1.0) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from transformers<5.0,>=4.46->table2text-pydanticai==0.1.0) (0.8.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (1.24.5)
Requirement already satisfied: idna>=2.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0,>=3.2->table2text-pydanticai==0.1.0) (3.18)
Requirement already satisfied: httpx2>=2.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from genai-prices>=0.0.62->pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (2.6.0)
Requirement already satisfied: anyio in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from httpx>=0.27->pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (4.14.2)
Requirement already satisfied: certifi in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from httpx>=0.27->pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (2026.6.17)
Requirement already satisfied: httpcore==1.* in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from httpx>=0.27->pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.27->pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (0.16.0)
Requirement already satisfied: httpcore2==2.6.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from httpx2>=2.0->genai-prices>=0.0.62->pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (2.6.0)
Requirement already satisfied: truststore>=0.10 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from httpx2>=2.0->genai-prices>=0.0.62->pydantic-ai-slim<2.0,>=1.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (0.10.4)
Requirement already satisfied: distro<2,>=1.7.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from openai>=2.29.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from openai>=2.29.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (0.16.0)
Requirement already satisfied: sniffio in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from openai>=2.29.0->pydantic-ai-slim[openai]<2.0,>=1.0->table2text-pydanticai==0.1.0) (1.3.1)
Requirement already satisfied: charset_normalizer<4,>=2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from requests->bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from requests->bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (2.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from sympy>=1.13.3->torch<3.0,>=2.3->table2text-pydanticai==0.1.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from jinja2->torch<3.0,>=2.3->table2text-pydanticai==0.1.0) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from matplotlib->bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from matplotlib->bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from matplotlib->bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from matplotlib->bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (1.5.0)
Requirement already satisfied: pillow>=9 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from matplotlib->bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (12.3.0)
Requirement already satisfied: pyparsing>=3 in ./table2text_pydanticai/.venv/lib/python3.11/site-packages (from matplotlib->bert-score<0.4,>=0.3.13->table2text-pydanticai==0.1.0) (3.3.2)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
Building wheels for collected packages: table2text-pydanticai
  Building editable for table2text-pydanticai (pyproject.toml) ... done
  Created wheel for table2text-pydanticai: filename=table2text_pydanticai-0.1.0-py3-none-any.whl size=2653 sha256=032235c021cd6e84f2206561b026ef007ee9caafa56e88fd84456bc368a936f3
  Stored in directory: /private/var/folders/vz/8jpx5pqj12n0_bxfqmp4z7d40000gn/T/pip-ephem-wheel-cache-wgh_e0ib/wheels/ba/15/72/95d1cc9655cd95e6dad76815137c749deb3bebe8a121f46d0f
Successfully built table2text-pydanticai
Installing collected packages: fsspec, dill, multiprocess, datasets, table2text-pydanticai
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2026.2.0
    Uninstalling fsspec-2026.2.0:
      Successfully uninstalled fsspec-2026.2.0
  Attempting uninstall: dill
    Found existing installation: dill 0.4.1
    Uninstalling dill-0.4.1:
      Successfully uninstalled dill-0.4.1
  Attempting uninstall: multiprocess━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [dill]
    Found existing installation: multiprocess 0.70.19━━━━━━━━━ 1/5 [dill]
    Uninstalling multiprocess-0.70.19:━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [dill]
      Successfully uninstalled multiprocess-0.70.19━━━━━━━━━━━ 1/5 [dill]
  Attempting uninstall: datasets━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/5 [dill]

In [ ]:
import json
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
    diagnostics_for_notebook,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

examples = read_examples(paths["prepared_examples"])

one_each = {}
for example in examples:
    one_each.setdefault(example.dataset_id, example)

five_examples = list(one_each.values())[1:2]

smoke_examples_path = project_dir / "evaluation/prepared/smoke_five.jsonl"
write_jsonl(smoke_examples_path, five_examples)

print("Smoke examples:", len(five_examples))
print([example.dataset_id for example in five_examples])

Smoke examples: 1
['totto']

In [ ]:
variants_payload = json.loads(paths["variant_config"].read_text(encoding="utf-8"))

smoke_variants = {
    "variants": [
        {**variant, "enabled": variant["variant_id"] == "full_system"}
        for variant in variants_payload["variants"]
    ]
}

smoke_variants_path = project_dir / "evaluation/config/variants_smoke.json"
smoke_variants_path.write_text(json.dumps(smoke_variants, indent=2), encoding="utf-8")

2470

In [ ]:
smoke_generations_path = project_dir / "evaluation/generations/smoke_five_generations.jsonl"
smoke_run_root = project_dir / "evaluation/generations/smoke_five_runs"

generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=smoke_examples_path,
    variants_path=smoke_variants_path,
    output_path=smoke_generations_path,
    run_root=smoke_run_root,
    resume=False,
)

generations[
    ["dataset_id", "variant_id", "error", "release_status", "writer_mode", "elapsed_seconds"]
]

In [ ]:
scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=smoke_generations_path,
    output_path=project_dir / "evaluation/results/smoke_five_reference_metrics_include_ineligible.jsonl",
    include_ineligible=True,
)

scores[["dataset_id", "variant_id", "metric_name", "status", "score"]]

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

              dataset_id   variant_id       metric_name   status     score
0   sportsett_basketball  full_system              bleu   scored  0.059159
1   sportsett_basketball  full_system              chrf   scored  0.357893
2   sportsett_basketball  full_system               ter   scored  0.834835
3   sportsett_basketball  full_system            rouge1   scored  0.423913
4   sportsett_basketball  full_system            rouge2   scored  0.105455
5   sportsett_basketball  full_system            rougeL   scored  0.159420
6   sportsett_basketball  full_system         rougeLsum   scored  0.159420
7   sportsett_basketball  full_system            meteor   scored  0.206169
8   sportsett_basketball  full_system  parent_precision  skipped       NaN
9   sportsett_basketball  full_system     parent_recall  skipped       NaN
10  sportsett_basketball  full_system         parent_f1  skipped       NaN
11  sportsett_basketball  full_system      bertscore_f1   scored -0.019974
12  sportsett_basketball  full_system       corpus_bleu   scored  0.059159
13  sportsett_basketball  full_system       corpus_chrf   scored  0.357893
14  sportsett_basketball  full_system        corpus_ter   scored  0.834835

In [ ]:
import json
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

examples = read_examples(paths["prepared_examples"])
totto_examples = [example for example in examples if example.dataset_id == "totto"][:1]

smoke_examples_path = project_dir / "evaluation/prepared/totto_smoke_1.jsonl"
write_jsonl(smoke_examples_path, totto_examples)

variants_payload = json.loads(paths["variant_config"].read_text(encoding="utf-8"))
smoke_variants = {
    "variants": [
        {**variant, "enabled": variant["variant_id"] == "full_system"}
        for variant in variants_payload["variants"]
    ]
}

smoke_variants_path = project_dir / "evaluation/config/variants_totto_smoke.json"
smoke_variants_path.write_text(json.dumps(smoke_variants, indent=2), encoding="utf-8")

smoke_generations_path = project_dir / "evaluation/generations/totto_smoke_generations.jsonl"
smoke_run_root = project_dir / "evaluation/generations/totto_smoke_runs"

generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=smoke_examples_path,
    variants_path=smoke_variants_path,
    output_path=smoke_generations_path,
    run_root=smoke_run_root,
    resume=False,
)

generations[
    ["dataset_id", "variant_id", "error", "release_status", "writer_mode", "elapsed_seconds"]
]

,dataset_id,variant_id,error,release_status,writer_mode,elapsed_seconds
0,totto,full_system,None,approved_with_warnings,llm_writer,86.33305

In [1]:
import json
from pathlib import Path

from table2text.evaluation import default_paths, generate_reports_for_notebook
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

examples = read_examples(paths["prepared_examples"])
totto_examples = [example for example in examples if example.dataset_id == "totto"]

# Change this index to test a different ToTTo example.
totto_index = 10
chosen = [totto_examples[totto_index]]

examples_path = project_dir / "evaluation/prepared/totto_one_test.jsonl"
write_jsonl(examples_path, chosen)

variants_payload = json.loads(paths["variant_config"].read_text(encoding="utf-8"))
variants = {
    "variants": [
        {**variant, "enabled": variant["variant_id"] == "full_system"}
        for variant in variants_payload["variants"]
    ]
}

variants_path = project_dir / "evaluation/config/variants_totto_one.json"
variants_path.write_text(json.dumps(variants, indent=2), encoding="utf-8")

generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=project_dir / "evaluation/generations/totto_one_test_generations.jsonl",
    run_root=project_dir / "evaluation/generations/totto_one_test_runs",
    resume=False,
)

display(generations[
    ["dataset_id", "example_id", "variant_id", "release_status", "writer_mode", "error"]
])

print("\nGenerated text:\n")
print(generations.iloc[0]["generated_text"])

print("\nRun artifact:\n")
print(generations.iloc[0]["pipeline_result_path"])

,dataset_id,example_id,variant_id,release_status,writer_mode,error
0,totto,totto-validation-1791,full_system,approved_with_warnings,deterministic_fallback,None

Generated text:

Ryan Hart placed 2nd in Street Fighter III: 3rd Strike at Hypespotting, placed 1st in Street Fighter X Tekken at Stunfest 2012, and won three times in a row in Street Fighter X Tekken at Cross Up Gamerbase.


Run artifact:

/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/totto_one_test_runs/full_system/totto/20260729T140046Z_2d8121e7f2/pipeline_result.json

In [7]:
import json
from pathlib import Path

from table2text.evaluation import default_paths, generate_reports_for_notebook
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

examples = read_examples(paths["prepared_examples"])

dataset_id = "e2e_nlg"

dataset_examples = [
    example for example in examples
    if example.dataset_id == dataset_id
]

print("Available examples:", len(dataset_examples))

example_index = 5  # change this: 0, 1, 2, 3, ...
one_example = dataset_examples[example_index]

print("Selected:", one_example.example_id)
print("Source:", one_example.source_text)
print("References:", one_example.references)

smoke_examples_path = project_dir / f"evaluation/prepared/{dataset_id}_example_{example_index}.jsonl"
write_jsonl(smoke_examples_path, [one_example])

variants_payload = json.loads(paths["variant_config"].read_text(encoding="utf-8"))
smoke_variants = {
    "variants": [
        {**variant, "enabled": variant["variant_id"] == "full_system"}
        for variant in variants_payload["variants"]
    ]
}

smoke_variants_path = project_dir / f"evaluation/config/variants_{dataset_id}_one.json"
smoke_variants_path.write_text(json.dumps(smoke_variants, indent=2), encoding="utf-8")

generations_path = project_dir / f"evaluation/generations/{dataset_id}_example_{example_index}_generations.jsonl"
run_root = project_dir / f"evaluation/generations/{dataset_id}_example_{example_index}_runs"

generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=smoke_examples_path,
    variants_path=smoke_variants_path,
    output_path=generations_path,
    run_root=run_root,
    resume=False,
)

generations[
    [
        "dataset_id",
        "example_id",
        "variant_id",
        "generated_text",
        "error",
        "release_status",
        "writer_mode",
    ]
]
print("\nGenerated text:\n")
print(generations.iloc[0]["generated_text"])

print("\nRun artifact:\n")
print(generations.iloc[0]["pipeline_result_path"])

Available examples: 30
Selected: e2e_nlg-test-191
Source: name[The Cricketers], eatType[coffee shop], customer rating[5 out of 5], familyFriendly[yes], near[Avalon]
References: ['The Cricketers is a kids-friendly coffee shop near Avalon with a rating of 3 out 5 stars.']

Generated text:

The Cricketers is a coffee shop that is family friendly, holds a customer rating of 5 out of 5, and is situated near Avalon.


Run artifact:

/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/e2e_nlg_example_5_runs/full_system/e2e_nlg/20260729T154440Z_4dad250fec/pipeline_result.json

In [ ]:
import json
from pathlib import Path

from table2text.evaluation import default_paths, generate_reports_for_notebook
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

dataset_id = "mlb_data_to_text"
example_index = 10  # change to 1, 2, 3... for a different MLB example

examples_path = project_dir / f"evaluation/prepared/{dataset_id}.jsonl"
examples = read_examples(examples_path)

one_example = examples[example_index]

print("Available examples:", len(examples))
print("Selected:", one_example.example_id)
print("References:", one_example.references[:2])

smoke_examples_path = project_dir / f"evaluation/prepared/{dataset_id}_example_{example_index}.jsonl"
write_jsonl(smoke_examples_path, [one_example])

variants_payload = json.loads(paths["variant_config"].read_text(encoding="utf-8"))
smoke_variants = {
    "variants": [
        {**variant, "enabled": variant["variant_id"] == "full_system"}
        for variant in variants_payload["variants"]
    ]
}

smoke_variants_path = project_dir / f"evaluation/config/variants_{dataset_id}_one.json"
smoke_variants_path.write_text(json.dumps(smoke_variants, indent=2), encoding="utf-8")

generations_path = project_dir / f"evaluation/generations/{dataset_id}_example_{example_index}_generations.jsonl"
run_root = project_dir / f"evaluation/generations/{dataset_id}_example_{example_index}_runs"

generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=smoke_examples_path,
    variants_path=smoke_variants_path,
    output_path=generations_path,
    run_root=run_root,
    resume=False,
)

generations[
    [
        "dataset_id",
        "example_id",
        "variant_id",
        "generated_text",
        "error",
        "release_status",
        "writer_mode",
    ]
]

Available examples: 20
Selected: GEM-mlb_data_to_text-test-192
References: ["ATLANTA -- Chipper Jones used a pregame meeting to ask his Atlanta Braves teammates for an intense start to a long homestand . The ninth inning may have provided more tension than Jones had expected . Yunel Escobar hit a sacrifice fly with the bases loaded in the bottom of ninth , giving the Atlanta Braves a 4 - 3 win over the Arizona Diamondbacks on Friday night after blowing a lead in the top of the inning . The Braves , coming off a 6 - 2 road trip that included series wins over Florida , Philadelphia and the New York Mets , opened a 10-game homestand with the worst home record in baseball . Jones , who hit his fourth homer , said the Braves improved to 6 - 9 at Turner Field by maintaining some of the passion they showed on the successful trip . `` Hopefully it 's something to build on . We started it on the road and we want to keep it going , he added . `` If you ca n't keep the home-field advantage and have it be an advantage for you , it 's going to be a long year . We 've got to win ballgames here . '' Jones ' third-inning homer gave the Braves a 3 - 2 lead that held until closer Mike Gonzalez ( 2 - 0 ) gave up a tying homer to Stephen Drew to lead off the ninth . It was the third blown save in nine chances for Gonzalez . With one out in the ninth , Jordan Schafer hit a single to right off Tony Pena ( 3 - 1 ) . Pinch-hitter Kelly Johnson walked and Omar Infante singled to center . Schafer , who hesitated between second and third to see if center fielder Chris Young would catch the ball , had to hold at third . Then Escobar 's fly to center allowed the speedy Schafer to score the winning run without a slide . Jones ' drive was the Braves ' sixth homer of the season at Turner Field , the low home total for any team in the majors . It was the ninth homer allowed by Doug Davis this season . The loss was the fourth straight and seventh in eight games for Arizona , which opened a 10-game road trip . Javier Vazquez struck out 10 in seven innings as the Braves took their fifth win in six games . Vazquez gave up five hits and two runs in seven innings . He gave up two runs in the first and then allowed only one baserunner as far as second the next six innings . Felipe Lopez hit Vazquez 's first pitch up the middle for a single and scored on Gerardo Parra 's triple to right . Parra scored on Justin Upton 's groundout for a 2 - 0 lead . The Braves took advantage of a throwing error by Davis to tie it in the second . Brian McCann and Jeff Francoeur opened the inning with singles . Casey Kotchman followed with a grounder to Davis , whose low throw skipped past first baseman Josh Whitesell for an error , allowing McCann to score . Francoeur scored on Schafer 's grounder . Davis gave up four hits and three runs -- two earned -- in six innings and , according to Hinch , was upset at being removed for a pinch hitter in the seventh after throwing only 80 pitches . Davis was not available for comment .", 'ATLANTA']

,dataset_id,example_id,variant_id,generated_text,error,release_status,writer_mode
0,mlb_data_to_text,GEM-mlb_data_to_text-test-192,full_system,# Braves Edge D-backs 4-3 in One-Run Contest\n...,None,human_review_required,llm_writer

In [1]:
import json
from pathlib import Path

from table2text.evaluation import default_paths, generate_reports_for_notebook
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

examples = read_examples(paths["prepared_examples"])

dataset_id = "sportsett_basketball"
example_id = "4934"

one_example = next(
    e for e in examples
    if e.dataset_id == dataset_id and e.example_id == example_id
)

examples_path = project_dir / f"evaluation/prepared/{dataset_id}_{example_id}.jsonl"
write_jsonl(examples_path, [one_example])

variants_payload = json.loads(paths["variant_config"].read_text(encoding="utf-8"))
variants = {
    "variants": [
        {**variant, "enabled": variant["variant_id"] == "full_system"}
        for variant in variants_payload["variants"]
    ]
}

variants_path = project_dir / f"evaluation/config/variants_{dataset_id}_{example_id}.json"
variants_path.write_text(json.dumps(variants, indent=2), encoding="utf-8")

generations_path = project_dir / f"evaluation/generations/{dataset_id}_{example_id}_generations.jsonl"
run_root = project_dir / f"evaluation/generations/{dataset_id}_{example_id}_runs"

generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=generations_path,
    run_root=run_root,
    resume=False,
)

generations[
    [
        "dataset_id",
        "example_id",
        "variant_id",
        "generated_text",
        "error",
        "release_status",
        "writer_mode",
        "elapsed_seconds",
    ]
]

,dataset_id,example_id,variant_id,generated_text,error,release_status,writer_mode,elapsed_seconds
0,sportsett_basketball,4934,full_system,The Philadelphia 76ers defeated the Memphis Gr...,None,approved,llm_writer,795.209452

In [2]:
print("\nGenerated text:\n")
print(generations.iloc[0]["generated_text"])

print("\nRun artifact:\n")
print(generations.iloc[0]["pipeline_result_path"])

Generated text:

The Philadelphia 76ers defeated the Memphis Grizzlies 103-95 on Sunday, December 2, 2018, at Wells Fargo Center in the 2018 season.
The final margin was eight points.
Philadelphia entered at 17-8 and Memphis at 13-9, playing their 25th and 22nd games respectively, with the 76ers third in the conference standings and the Grizzlies sixth.
Philadelphia led 26-25 after the first quarter, 54-44 at halftime, and 78-68 entering the fourth.
Philadelphia stretched its lead in the second quarter, outscoring Memphis 28-19, while the third quarter was even at 24-24.
Memphis outscored Philadelphia 27-25 in the fourth quarter, but the 76ers closed out the 103-95 victory.
J.J. Redick led all scorers with 24 points; Jimmy Butler and Mike Conley tied with 21 apiece, and Ben Simmons added 19.
Redick's total was built on a game-leading nine made field goals, and he, Butler, and Conley each attempted 17 shots.
Joel Embiid contributed 15 points and a game-high 14 rebounds, with Ben Simmons grabbing 12 rebounds.
T.J. McConnell posted a game-high plus/minus of +16, followed by Joel Embiid at +13.
Kyle Anderson finished with the highest field-goal percentage at 100 percent, while Ben Simmons shot 80 percent from the field.
Memphis held the edge from three-point range, making 11 of 28 attempts to Philadelphia's 8 of 22, with J.J. Redick, Mike Conley, and Garrett Temple each connecting three times.
Philadelphia countered at the free-throw line, converting 23 of 30 attempts to Memphis' 18 of 23, with Joel Embiid and Jimmy Butler each making seven.
Memphis also led in defensive disruption, recording 7 steals and 7 blocks to Philadelphia's 5 and 2, with JaMychal Green collecting 4 steals and Jaren Jackson blocking 3 shots.
The 76ers finished with a 22-19 team-assist advantage, paced by Ben Simmons' game-high 6 assists, with Mike Muscala, Mike Conley, and Kyle Anderson each recording 5.
These comparisons describe only the supplied event; they do not establish why the result occurred and do not support claims about broader team performance.


Run artifact:

/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/sportsett_basketball_4934_runs/full_system/sportsett_basketball/20260801T151226Z_7ccd0b3a42/pipeline_result.json

In [1]:
import json
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
    score_deepeval_for_notebook,
)
from table2text.evaluation.datasets import read_examples, write_jsonl
from table2text.evaluation.generation import read_generations

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

dataset_id = "sportsett_basketball"
example_id = "4934"

# 1. Select one SportSett example
examples = read_examples(paths["prepared_examples"])
example = next(
    e for e in examples
    if e.dataset_id == dataset_id and e.example_id == example_id
)

examples_path = project_dir / "evaluation/prepared/sportsett_raw_baseline_one.jsonl"
write_jsonl(examples_path, [example])

# 2. Generate raw DeepSeek V4-Pro baseline
variants_path = project_dir / "evaluation/config/variants_raw_deepseek_v4_flash.json"
variants_path.write_text(
    json.dumps(
        {
            "variants": [
                {
                    "variant_id": "raw_deepseek_v4_flash",
                    "enabled": True,
                    "backend": "callable",
                    "description": "Raw single-LLM DeepSeek baseline from source data only.",
                    "settings_overrides": {
                        "raw_baseline_model": "deepseek-v4-flash",
                        "raw_baseline_max_source_characters": 100000,
                        "raw_baseline_max_output_tokens": 3000,
                        "raw_baseline_temperature": 0.2,
                    },
                    "callable_path": "table2text.evaluation_backends.single_agent_baseline",
                    "command": [],
                    "precomputed_path": None,
                    "repetitions": 1,
                    "seeds": [42],
                }
            ]
        },
        indent=2,
    ),
    encoding="utf-8",
)

raw_generations_path = project_dir / "evaluation/generations/sportsett_raw_deepseek_v4_flash_generations.jsonl"
raw_run_root = project_dir / "evaluation/generations/sportsett_raw_deepseek_v4_flash_runs"

raw_generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=raw_generations_path,
    run_root=raw_run_root,
    resume=False,
)

display(raw_generations[
    ["dataset_id", "example_id", "variant_id", "generated_text", "error", "elapsed_seconds"]
])

,dataset_id,example_id,variant_id,generated_text,error,elapsed_seconds
0,sportsett_basketball,4934,raw_deepseek_v4_flash,The Philadelphia 76ers defeated the Memphis Gr...,None,18.040106

In [2]:
import json
import random
from pathlib import Path

import pandas as pd

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

# ---- choose run size here ----
DATASET_ID = "sportsett_basketball"
N_EXAMPLES = 1
RANDOM_SAMPLE = False
SEED = 42

# Optional AlignScore setup.
# Leave as None if you have not created the separate AlignScore venv yet.
ALIGNSCORE_PYTHON = None
# Example:
# ALIGNSCORE_PYTHON = project_dir / ".venv-alignscore/bin/python"

# ---- select examples ----
examples = [
    example
    for example in read_examples(paths["prepared_examples"])
    if example.dataset_id == DATASET_ID
]

if not examples:
    raise ValueError(
        f"No prepared examples found for {DATASET_ID}. "
        "Run prepare_examples_for_notebook(project_dir) first."
    )

if RANDOM_SAMPLE:
    rng = random.Random(SEED)
    selected_examples = rng.sample(examples, min(N_EXAMPLES, len(examples)))
else:
    selected_examples = examples[:N_EXAMPLES]

run_name = f"{DATASET_ID}_{len(selected_examples)}"

examples_path = project_dir / f"evaluation/prepared/{run_name}.jsonl"
generations_path = project_dir / f"evaluation/generations/{run_name}_generations.jsonl"
run_root = project_dir / f"evaluation/generations/{run_name}_runs"
variants_path = project_dir / f"evaluation/config/variants_{run_name}.json"
metrics_path = project_dir / f"evaluation/config/metrics_{run_name}.json"
metrics_output_path = project_dir / f"evaluation/results/{run_name}_reference_metrics.jsonl"

write_jsonl(examples_path, selected_examples)

print("Selected examples:", len(selected_examples))
print("Example IDs:", [example.example_id for example in selected_examples])

# ---- use only full_system variant ----
variants_payload = json.loads(paths["variant_config"].read_text(encoding="utf-8"))
smoke_variants = {
    "variants": [
        {**variant, "enabled": variant["variant_id"] == "full_system"}
        for variant in variants_payload["variants"]
    ]
}
variants_path.write_text(json.dumps(smoke_variants, indent=2), encoding="utf-8")

# ---- metric config: BLEU/ROUGE/etc + PARENT + HHEM + AlignScore ----
metric_payload = json.loads(paths["metric_config"].read_text(encoding="utf-8"))

metric_payload["reference_metrics"]["enabled_metrics"] = [
    "bleu",
    "chrf",
    "ter",
    "rouge1",
    "rouge2",
    "rougeL",
    "rougeLsum",
    "meteor",
    "bertscore",
    #"parent",
    #"hhem",
    #"alignscore",
]

metric_payload["reference_metrics"]["hhem_model"] = (
    "vectara/hallucination_evaluation_model"
)
metric_payload["reference_metrics"]["hhem_threshold"] = 0.5
metric_payload["reference_metrics"]["hhem_batch_size"] = 16
metric_payload["reference_metrics"]["hhem_device"] = None

# metric_payload["reference_metrics"]["alignscore_python_executable"] = (
#     str(ALIGNSCORE_PYTHON) if ALIGNSCORE_PYTHON else None
# )
# metric_payload["reference_metrics"]["alignscore_model_size"] = "base"
# metric_payload["reference_metrics"]["alignscore_device"] = "cpu"
# metric_payload["reference_metrics"]["alignscore_threshold"] = 0.5

metrics_path.write_text(json.dumps(metric_payload, indent=2), encoding="utf-8")

# ---- generate reports ----
generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=generations_path,
    run_root=run_root,
    resume=False,
)

display(
    generations[
        [
            "dataset_id",
            "example_id",
            "variant_id",
            "error",
            "release_status",
            "writer_mode",
            "elapsed_seconds",
            "pipeline_result_path",
        ]
    ]
)

# ---- score reference + local factuality metrics ----
scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=generations_path,
    metric_config_path=metrics_path,
    output_path=metrics_output_path,
    include_ineligible=True,
)

# ---- output vs reference table ----
references_by_id = {
    example.example_id: example.references
    for example in selected_examples
}

comparison = generations.copy()
comparison["reference"] = comparison["example_id"].map(
    lambda example_id: references_by_id.get(example_id, [""])[0]
)
comparison["all_references"] = comparison["example_id"].map(
    lambda example_id: references_by_id.get(example_id, [])
)

comparison_table = comparison[
    [
        "dataset_id",
        "example_id",
        "variant_id",
        "generated_text",
        "reference",
        "all_references",
        "release_status",
        "writer_mode",
        "pipeline_result_path",
    ]
]

display(comparison_table)

# ---- metric score table ----
score_table = scores.pivot_table(
    index=["dataset_id", "example_id", "variant_id"],
    columns="metric_name",
    values="score",
    aggfunc="first",
).reset_index()

display(score_table)

# ---- metric status table, useful for HHEM / AlignScore availability ----
status_table = scores.pivot_table(
    index=["dataset_id", "example_id", "variant_id"],
    columns="metric_name",
    values="status",
    aggfunc="first",
).reset_index()

display(status_table)

print("Examples:", examples_path)
print("Generations:", generations_path)
print("Run artifacts:", run_root)
print("Metric rows:", metrics_output_path)

Selected examples: 1
Example IDs: ['4934']

,dataset_id,example_id,variant_id,error,release_status,writer_mode,elapsed_seconds,pipeline_result_path
0,sportsett_basketball,4934,full_system,None,approved_with_warnings,auditor_repaired,1233.027671,/Users/realgobs/Documents/MScproject/table2tex...

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

,dataset_id,example_id,variant_id,generated_text,reference,all_references,release_status,writer_mode,pipeline_result_path
0,sportsett_basketball,4934,full_system,The Philadelphia 76ers defeated the Memphis Gr...,The Philadelphia 76ers defeated the visiting M...,[The Philadelphia 76ers defeated the visiting ...,approved_with_warnings,auditor_repaired,/Users/realgobs/Documents/MScproject/table2tex...

metric_name,dataset_id,example_id,variant_id,bertscore_f1,bleu,chrf,corpus_bleu,corpus_chrf,corpus_ter,meteor,rouge1,rouge2,rougeL,rougeLsum,ter
0,sportsett_basketball,4934,full_system,0.843521,0.104848,0.393361,0.104848,0.393361,0.876877,0.222544,0.433281,0.144882,0.22606,0.22606,0.876877

metric_name,dataset_id,example_id,variant_id,bertscore_f1,bleu,chrf,corpus_bleu,corpus_chrf,corpus_ter,meteor,rouge1,rouge2,rougeL,rougeLsum,ter
0,sportsett_basketball,4934,full_system,scored,scored,scored,scored,scored,scored,scored,scored,scored,scored,scored,scored

Examples: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/prepared/sportsett_basketball_1.jsonl
Generations: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/sportsett_basketball_1_generations.jsonl
Run artifacts: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/sportsett_basketball_1_runs
Metric rows: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/sportsett_basketball_1_reference_metrics.jsonl

In [1]:
import json
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    score_reference_metrics_for_notebook,
)

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

generations_path = project_dir / "evaluation/generations/sportsett_basketball_1_generations.jsonl"
metrics_path = project_dir / "evaluation/config/metrics_sportsett_basketball_1.json"
metrics_output_path = project_dir / "evaluation/results/sportsett_basketball_1_reference_metrics.jsonl"

metric_payload = json.loads(paths["metric_config"].read_text(encoding="utf-8"))

metric_payload["reference_metrics"]["enabled_metrics"] = [
    "bleu",
    "chrf",
    "ter",
    "rouge1",
    "rouge2",
    "rougeL",
    "rougeLsum",
    "meteor",
    "bertscore",
    "parent",
    "hhem",
    "alignscore",
]

# Leave AlignScore disabled/unavailable unless you have the separate venv.
metric_payload["reference_metrics"]["alignscore_python_executable"] = None

metrics_path.write_text(json.dumps(metric_payload, indent=2), encoding="utf-8")

scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=generations_path,
    metric_config_path=metrics_path,
    output_path=metrics_output_path,
    include_ineligible=True,
)

display(
    scores[
        [
            "dataset_id",
            "example_id",
            "variant_id",
            "metric_family",
            "metric_name",
            "status",
            "score",
            "error",
        ]
    ]
)

score_table = scores.pivot_table(
    index=["dataset_id", "example_id", "variant_id"],
    columns="metric_name",
    values="score",
    aggfunc="first",
).reset_index()

display(score_table)

status_table = scores.pivot_table(
    index=["dataset_id", "example_id", "variant_id"],
    columns="metric_name",
    values="status",
    aggfunc="first",
).reset_index()

display(status_table)

print("Metric rows:", metrics_output_path)

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
You are using a model of type HHEMv2Config to instantiate a model of type HHEMv2. This is not supported for all configurations of models and can yield errors.
Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

,dataset_id,example_id,variant_id,metric_family,metric_name,status,score,error
0,sportsett_basketball,4934,full_system,lexical,bleu,scored,0.088285,None
1,sportsett_basketball,4934,full_system,lexical,chrf,scored,0.420958,None
2,sportsett_basketball,4934,full_system,lexical,ter,scored,1.192192,None
3,sportsett_basketball,4934,full_system,lexical,rouge1,scored,0.451697,None
4,sportsett_basketball,4934,full_system,lexical,rouge2,scored,0.138743,None
5,sportsett_basketball,4934,full_system,lexical,rougeL,scored,0.216710,None
6,sportsett_basketball,4934,full_system,lexical,rougeLsum,scored,0.216710,None
7,sportsett_basketball,4934,full_system,lexical_semantic,meteor,scored,0.282901,None
8,sportsett_basketball,4934,full_system,table_aware,parent_precision,skipped,NaN,None
9,sportsett_basketball,4934,full_system,table_aware,parent_recall,skipped,NaN,None
10,sportsett_basketball,4934,full_system,table_aware,parent_f1,skipped,NaN,None
11,sportsett_basketball,4934,full_system,external_factuality,hhem_2_1_open_mean_support,scored,0.090191,None
12,sportsett_basketball,4934,full_system,external_factuality,hhem_2_1_open_min_sentence_support,scored,0.003497,None
13,sportsett_basketball,4934,full_system,external_factuality,hhem_2_1_open_unsupported_sentence_rate,scored,0.950000,None
14,sportsett_basketball,4934,full_system,external_factuality,alignscore_base,scored,0.218447,None
15,sportsett_basketball,4934,full_system,semantic,bertscore_f1,scored,0.846570,None
16,sportsett_basketball,4934,full_system,lexical_corpus,corpus_bleu,scored,0.088285,None
17,sportsett_basketball,4934,full_system,lexical_corpus,corpus_chrf,scored,0.420958,None
18,sportsett_basketball,4934,full_system,lexical_corpus,corpus_ter,scored,1.192192,None

metric_name,dataset_id,example_id,variant_id,alignscore_base,bertscore_f1,bleu,chrf,corpus_bleu,corpus_chrf,corpus_ter,hhem_2_1_open_mean_support,hhem_2_1_open_min_sentence_support,hhem_2_1_open_unsupported_sentence_rate,meteor,rouge1,rouge2,rougeL,rougeLsum,ter
0,sportsett_basketball,4934,full_system,0.218447,0.84657,0.088285,0.420958,0.088285,0.420958,1.192192,0.090191,0.003497,0.95,0.282901,0.451697,0.138743,0.21671,0.21671,1.192192

metric_name,dataset_id,example_id,variant_id,alignscore_base,bertscore_f1,bleu,chrf,corpus_bleu,corpus_chrf,corpus_ter,...,hhem_2_1_open_unsupported_sentence_rate,meteor,parent_f1,parent_precision,parent_recall,rouge1,rouge2,rougeL,rougeLsum,ter
0,sportsett_basketball,4934,full_system,scored,scored,scored,scored,scored,scored,scored,...,scored,scored,skipped,skipped,skipped,scored,scored,scored,scored,scored

Metric rows: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/sportsett_basketball_1_reference_metrics.jsonl

In [1]:
from pathlib import Path
from table2text.evaluation import score_deepeval_for_notebook

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")

deepeval_scores = score_deepeval_for_notebook(
    project_dir,
    generations_path=project_dir / "evaluation/generations/sportsett_basketball_1_generations.jsonl",
    metric_config_path=project_dir / "evaluation/config/metrics_sportsett_basketball_1.json",
    output_path=project_dir / "evaluation/results/sportsett_basketball_1_deepeval_metrics.jsonl",
    resume=False,
)

deepeval_scores[
    ["dataset_id", "example_id", "metric_name", "status", "score", "reason", "error"]
]

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/rich/live.py:260:
UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

,dataset_id,example_id,metric_name,status,score,reason,error
0,sportsett_basketball,4934,deepeval_faithfulness,scored,0.951220,The score is 0.95 because the actual output ha...,None
1,sportsett_basketball,4934,deepeval_summarization,scored,0.071429,The score is 0.07 because the summary fabricat...,None
2,sportsett_basketball,4934,geval_coherence,scored,1.000000,"The response is clear and unambiguous, present...",None
3,sportsett_basketball,4934,geval_factual_correctness,scored,1.000000,All factual claims in the output are fully sup...,None
4,sportsett_basketball,4934,geval_reference_adequacy,scored,0.400000,"The actual output includes the final score, qu...",None
5,sportsett_basketball,4934,geval_task_relevance,scored,1.000000,The Actual Output thoroughly covers all critic...,None
6,sportsett_basketball,4934,geval_usefulness,scored,1.000000,The output accurately extracts and presents al...,None

In [2]:
from pathlib import Path
import pandas as pd
import json

path = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/sportsett_basketball_1_deepeval_metrics.jsonl")

rows = [
    json.loads(line)
    for line in path.read_text(encoding="utf-8").splitlines()
    if line.strip()
]

df = pd.DataFrame(rows)
df[["dataset_id", "example_id", "metric_name", "judge_model", "status", "score", "success", "reason", "error"]]

,dataset_id,example_id,metric_name,judge_model,status,score,success,reason,error
0,sportsett_basketball,4934,deepeval_faithfulness,deepseek:deepseek-v4-pro,scored,0.951220,True,The score is 0.95 because the actual output ha...,None
1,sportsett_basketball,4934,deepeval_summarization,deepseek:deepseek-v4-pro,scored,0.071429,False,The score is 0.07 because the summary fabricat...,None
2,sportsett_basketball,4934,geval_coherence,deepseek:deepseek-v4-pro,scored,1.000000,True,"The response is clear and unambiguous, present...",None
3,sportsett_basketball,4934,geval_factual_correctness,deepseek:deepseek-v4-pro,scored,1.000000,True,All factual claims in the output are fully sup...,None
4,sportsett_basketball,4934,geval_reference_adequacy,deepseek:deepseek-v4-pro,scored,0.400000,False,"The actual output includes the final score, qu...",None
5,sportsett_basketball,4934,geval_task_relevance,deepseek:deepseek-v4-pro,scored,1.000000,True,The Actual Output thoroughly covers all critic...,None
6,sportsett_basketball,4934,geval_usefulness,deepseek:deepseek-v4-pro,scored,1.000000,True,The output accurately extracts and presents al...,None

In [2]:
import json
from pathlib import Path
import pandas as pd

from table2text.evaluation import (
    default_paths,
    score_reference_metrics_for_notebook,
    score_deepeval_for_notebook,
)
from table2text.evaluation.generation import read_generations
from table2text.evaluation.datasets import write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

generations_path = project_dir / "evaluation/generations/sportsett_basketball_1_generations.jsonl"

records = [
    record for record in read_generations(generations_path)
    if record.error is None and record.generated_text.strip()
]

reference_records = []
for record in records:
    for i, reference in enumerate(record.references):
        reference_records.append(
            record.model_copy(
                update={
                    "generation_id": f"{record.generation_id}::human_reference::{i}",
                    "variant_id": f"human_reference_{i + 1}",
                    "generated_text": reference,
                    "writer_mode": "provided_reference",
                    "release_status": "reference",
                    "primary_evaluation_eligible": True,
                    "primary_evaluation_reason": None,
                }
            )
        )

combined_path = project_dir / "evaluation/generations/source_grounded_generated_and_references.jsonl"
write_jsonl(combined_path, records + reference_records)

base_metrics = json.loads(paths["metric_config"].read_text(encoding="utf-8"))

source_metric_config = base_metrics.copy()
source_metric_config["reference_metrics"] = {
    **source_metric_config["reference_metrics"],
    "enabled_metrics": ["hhem", "alignscore"],
    "external_factuality_context": "source_text",
    "external_context_max_characters": 100000,
    "hhem_context_max_characters": 1500,
}
source_metric_config["deepeval"] = {
    **source_metric_config["deepeval"],
    "run_summarization": False,
    "run_reference_adequacy": False,
    "run_faithfulness": True,
    "run_factual_correctness": True,
    "run_task_relevance": True,
    "run_coherence": True,
    "run_usefulness": True,
}

source_config_path = project_dir / "evaluation/config/metrics_source_grounded.json"
source_config_path.write_text(json.dumps(source_metric_config, indent=2), encoding="utf-8")

source_local_scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=combined_path,
    metric_config_path=source_config_path,
    output_path=project_dir / "evaluation/results/source_grounded_local_metrics.jsonl",
)

source_judge_scores = score_deepeval_for_notebook(
    project_dir,
    generations_path=combined_path,
    metric_config_path=source_config_path,
    output_path=project_dir / "evaluation/results/source_grounded_deepeval_metrics.jsonl",
    resume=False,
)

reference_similarity_config = base_metrics.copy()
reference_similarity_config["reference_metrics"] = {
    **reference_similarity_config["reference_metrics"],
    "enabled_metrics": [
        "bleu",
        "chrf",
        "ter",
        "rouge1",
        "rouge2",
        "rougeL",
        "rougeLsum",
        "meteor",
        "bertscore",
        "parent",
    ],
}

reference_config_path = project_dir / "evaluation/config/metrics_reference_similarity.json"
reference_config_path.write_text(json.dumps(reference_similarity_config, indent=2), encoding="utf-8")

reference_similarity_scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=generations_path,
    metric_config_path=reference_config_path,
    output_path=project_dir / "evaluation/results/reference_similarity_metrics.jsonl",
)

source_scores = pd.concat(
    [
        source_local_scores.assign(metric_source="local_source_grounded"),
        source_judge_scores.assign(metric_source="deepeval_source_grounded"),
    ],
    ignore_index=True,
)

source_scores["candidate_type"] = source_scores["variant_id"].apply(
    lambda value: "provided_reference" if str(value).startswith("human_reference") else "generated"
)

source_comparison = (
    source_scores[source_scores["status"].eq("scored")]
    .groupby(["dataset_id", "example_id", "metric_name", "candidate_type"], as_index=False)["score"]
    .mean()
    .pivot_table(
        index=["dataset_id", "example_id", "metric_name"],
        columns="candidate_type",
        values="score",
        aggfunc="mean",
    )
    .reset_index()
)

if {"generated", "provided_reference"}.issubset(source_comparison.columns):
    source_comparison["generated_minus_reference"] = (
        source_comparison["generated"] - source_comparison["provided_reference"]
    )

display(source_comparison)
display(reference_similarity_scores[["dataset_id", "example_id", "variant_id", "metric_name", "status", "score"]])

You are using a model of type HHEMv2Config to instantiate a model of type HHEMv2. This is not supported for all configurations of models and can yield errors.
Token indices sequence length is longer than the specified maximum sequence length for this model (632 > 512). Running this sequence through the model will result in indexing errors

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/rich/live.py:260:
UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

KeyboardInterrupt:

In [ ]:
import json
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
    score_deepeval_for_notebook,
)
from table2text.evaluation.datasets import read_examples, write_jsonl
from table2text.evaluation.generation import read_generations

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

dataset_id = "sportsett_basketball"
example_id = "4934"

# 1. Select one SportSett example
examples = read_examples(paths["prepared_examples"])
example = next(
    e for e in examples
    if e.dataset_id == dataset_id and e.example_id == example_id
)

examples_path = project_dir / "evaluation/prepared/sportsett_raw_baseline_one.jsonl"
write_jsonl(examples_path, [example])

# 2. Generate raw DeepSeek V4-Pro baseline
variants_path = project_dir / "evaluation/config/variants_raw_deepseek_v4_flash.json"
variants_path.write_text(
    json.dumps(
        {
            "variants": [
                {
                    "variant_id": "raw_deepseek_v4_flash",
                    "enabled": True,
                    "backend": "callable",
                    "description": "Raw single-LLM DeepSeek baseline from source data only.",
                    "settings_overrides": {
                        "raw_baseline_model": "deepseek-v4-flash",
                        "raw_baseline_max_source_characters": 100000,
                        "raw_baseline_max_output_tokens": 3000,
                        "raw_baseline_temperature": 0.2,
                    },
                    "callable_path": "table2text.evaluation_backends.single_agent_baseline",
                    "command": [],
                    "precomputed_path": None,
                    "repetitions": 1,
                    "seeds": [42],
                }
            ]
        },
        indent=2,
    ),
    encoding="utf-8",
)

raw_generations_path = project_dir / "evaluation/generations/sportsett_raw_deepseek_v4_flash_generations.jsonl"
raw_run_root = project_dir / "evaluation/generations/sportsett_raw_deepseek_v4_flash_runs"

raw_generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=raw_generations_path,
    run_root=raw_run_root,
    resume=False,
)

display(raw_generations[
    ["dataset_id", "example_id", "variant_id", "generated_text", "error", "elapsed_seconds"]
])

# 3. Build comparison files: full system + raw baseline + human references
full_path = project_dir / "evaluation/generations/sportsett_basketball_1_generations.jsonl"

full_records = read_generations(full_path)
raw_records = read_generations(raw_generations_path)
system_records = full_records + raw_records

base = full_records[0]
reference_records = []
for index, reference in enumerate(base.references):
    reference_records.append(
        base.model_copy(
            update={
                "generation_id": f"{base.generation_id}::human_reference::{index}",
                "variant_id": f"human_reference_{index + 1}",
                "generated_text": reference,
                "backend": "precomputed",
                "writer_mode": "provided_reference",
                "release_status": "reference",
                "approved_for_release": True,
                "primary_evaluation_eligible": True,
                "primary_evaluation_reason": None,
                "metadata": {
                    "baseline_type": "provided_reference",
                    "reference_index": index,
                },
                "error": None,
            }
        )
    )

source_comparison_path = project_dir / "evaluation/generations/sportsett_4934_source_grounded_comparison.jsonl"
reference_similarity_path = project_dir / "evaluation/generations/sportsett_4934_reference_similarity_candidates.jsonl"

write_jsonl(source_comparison_path, system_records + reference_records)
write_jsonl(reference_similarity_path, system_records)

# 4. Create metric configs
base_metrics = json.loads(paths["metric_config"].read_text(encoding="utf-8"))

source_metric_config = base_metrics.copy()
source_metric_config["experiment_id"] = "sportsett_4934_source_grounded_comparison"
source_metric_config["reference_metrics"] = {
    **source_metric_config["reference_metrics"],
    "enabled_metrics": ["hhem", "alignscore"],
    "external_factuality_context": "source_text",
    "external_context_max_characters": 100000,
    "hhem_context_max_characters": 1500,
}
source_metric_config["deepeval"] = {
    **source_metric_config["deepeval"],
    "run_summarization": False,
    "run_reference_adequacy": False,
    "run_faithfulness": True,
    "run_factual_correctness": True,
    "run_task_relevance": True,
    "run_coherence": True,
    "run_usefulness": True,
}

source_config_path = project_dir / "evaluation/config/metrics_sportsett_4934_source_grounded_comparison.json"
source_config_path.write_text(json.dumps(source_metric_config, indent=2), encoding="utf-8")

reference_metric_config = base_metrics.copy()
reference_metric_config["experiment_id"] = "sportsett_4934_reference_similarity_comparison"
reference_metric_config["reference_metrics"] = {
    **reference_metric_config["reference_metrics"],
    "enabled_metrics": [
        "bleu",
        "chrf",
        "ter",
        "rouge1",
        "rouge2",
        "rougeL",
        "rougeLsum",
        "meteor",
        "bertscore",
        "parent",
    ],
}

reference_config_path = project_dir / "evaluation/config/metrics_sportsett_4934_reference_similarity_comparison.json"
reference_config_path.write_text(json.dumps(reference_metric_config, indent=2), encoding="utf-8")

# 5. Run local source-grounded metrics
source_local_scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=source_comparison_path,
    metric_config_path=source_config_path,
    output_path=project_dir / "evaluation/results/sportsett_4934_source_grounded_local_metrics.jsonl",
)

display(source_local_scores[
    ["variant_id", "metric_name", "status", "score"]
])

# 6. Run reference-similarity metrics
reference_scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=reference_similarity_path,
    metric_config_path=reference_config_path,
    output_path=project_dir / "evaluation/results/sportsett_4934_reference_similarity_metrics.jsonl",
)

display(reference_scores[
    ["variant_id", "metric_name", "status", "score"]
])

# 7. Optional: DeepEval source-grounded judge metrics
# This uses your DEEPSEEK_API_KEY and may take a few minutes.
deepeval_scores = score_deepeval_for_notebook(
    project_dir,
    generations_path=source_comparison_path,
    metric_config_path=source_config_path,
    output_path=project_dir / "evaluation/results/sportsett_4934_source_grounded_deepeval_metrics.jsonl",
    resume=False,
)

display(deepeval_scores[
    ["variant_id", "metric_name", "status", "score", "success"]
])

,dataset_id,example_id,variant_id,generated_text,error,elapsed_seconds
0,sportsett_basketball,4934,raw_deepseek_v4_pro,"J.J. Redick scored a game-high 24 points, and ...",None,32.363554

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/pydantic/main.py:475: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='backend', input_value='precomputed', input_type=str])
  return self.__pydantic_serializer__.to_python(
/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
You are using a model of type HHEMv2Config to instantiate a model of type HHEMv2. This is not supported for all configurations of models and can yield errors.
Token indices sequence length is longer than the specified maximum sequence length for this model (1006 > 512). Running this sequence through the model will result in indexing errors

,variant_id,metric_name,status,score
0,full_system,hhem_2_1_open_mean_support,scored,0.014343
1,full_system,hhem_2_1_open_min_sentence_support,scored,0.004946
2,full_system,hhem_2_1_open_unsupported_sentence_rate,scored,1.000000
3,raw_deepseek_v4_pro,hhem_2_1_open_mean_support,scored,0.012169
4,raw_deepseek_v4_pro,hhem_2_1_open_min_sentence_support,scored,0.003727
5,raw_deepseek_v4_pro,hhem_2_1_open_unsupported_sentence_rate,scored,1.000000
6,human_reference_1,hhem_2_1_open_mean_support,scored,0.010053
7,human_reference_1,hhem_2_1_open_min_sentence_support,scored,0.004780
8,human_reference_1,hhem_2_1_open_unsupported_sentence_rate,scored,1.000000
9,human_reference_2,hhem_2_1_open_mean_support,scored,0.010113
10,human_reference_2,hhem_2_1_open_min_sentence_support,scored,0.004523
11,human_reference_2,hhem_2_1_open_unsupported_sentence_rate,scored,1.000000
12,full_system,alignscore_base,scored,0.245136
13,raw_deepseek_v4_pro,alignscore_base,scored,0.269591
14,human_reference_1,alignscore_base,scored,0.212146
15,human_reference_2,alignscore_base,scored,0.185650

Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

             variant_id       metric_name   status     score
0           full_system              bleu   scored  0.088285
1           full_system              chrf   scored  0.420958
2           full_system               ter   scored  1.192192
3           full_system            rouge1   scored  0.451697
4           full_system            rouge2   scored  0.138743
5           full_system            rougeL   scored  0.216710
6           full_system         rougeLsum   scored  0.216710
7           full_system            meteor   scored  0.282901
8           full_system  parent_precision  skipped       NaN
9           full_system     parent_recall  skipped       NaN
10          full_system         parent_f1  skipped       NaN
11  raw_deepseek_v4_pro              bleu   scored  0.117347
12  raw_deepseek_v4_pro              chrf   scored  0.374327
13  raw_deepseek_v4_pro               ter   scored  0.828829
14  raw_deepseek_v4_pro            rouge1   scored  0.484375
15  raw_deepseek_v4_pro            rouge2   scored  0.215686
16  raw_deepseek_v4_pro            rougeL   scored  0.265625
17  raw_deepseek_v4_pro         rougeLsum   scored  0.265625
18  raw_deepseek_v4_pro            meteor   scored  0.244297
19  raw_deepseek_v4_pro  parent_precision  skipped       NaN
20  raw_deepseek_v4_pro     parent_recall  skipped       NaN
21  raw_deepseek_v4_pro         parent_f1  skipped       NaN
22          full_system      bertscore_f1   scored  0.846570
23  raw_deepseek_v4_pro      bertscore_f1   scored  0.847529
24          full_system       corpus_bleu   scored  0.088285
25          full_system       corpus_chrf   scored  0.420958
26          full_system        corpus_ter   scored  1.192192
27  raw_deepseek_v4_pro       corpus_bleu   scored  0.117347
28  raw_deepseek_v4_pro       corpus_chrf   scored  0.374327
29  raw_deepseek_v4_pro        corpus_ter   scored  0.828829

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/rich/live.py:260:
UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 1 time(s)...
INFO:deepeval.retry.deepseek:Retrying in 1.5649897015717908 s (attempt 1) after TimeoutError('call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt.')
ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 2 time(s)...

ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 1 time(s)...
INFO:deepeval.retry.deepseek:Retrying in 1.2579969048840562 s (attempt 1) after TimeoutError('call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt.')
ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 2 time(s)...

ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 1 time(s)...
INFO:deepeval.retry.deepseek:Retrying in 2.3687692485672045 s (attempt 1) after TimeoutError('call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt.')
ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 2 time(s)...

ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 1 time(s)...
INFO:deepeval.retry.deepseek:Retrying in 1.2597487865355526 s (attempt 1) after TimeoutError('call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt.')
ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 2 time(s)...

ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 1 time(s)...
INFO:deepeval.retry.deepseek:Retrying in 1.153394891940672 s (attempt 1) after TimeoutError('call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt.')
ERROR:deepeval.retry.deepseek:call timed out after 88.5s (per attempt). Increase DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE (None disables) or reduce work per attempt. Retrying: 2 time(s)...

             variant_id                metric_name  status     score success
0           full_system      deepeval_faithfulness   error       NaN    None
1           full_system            geval_coherence  scored  1.000000    True
2           full_system  geval_factual_correctness  scored  1.000000    True
3           full_system       geval_task_relevance  scored  0.700000    True
4           full_system           geval_usefulness  scored  1.000000    True
5     human_reference_1      deepeval_faithfulness  scored  0.941176    True
6     human_reference_1            geval_coherence  scored  1.000000    True
7     human_reference_1  geval_factual_correctness  scored  0.200000   False
8     human_reference_1       geval_task_relevance  scored  0.000000   False
9     human_reference_1           geval_usefulness  scored  0.300000   False
10    human_reference_2      deepeval_faithfulness  scored  0.950000    True
11    human_reference_2            geval_coherence   error       NaN    None
12    human_reference_2  geval_factual_correctness   error       NaN    None
13    human_reference_2       geval_task_relevance   error       NaN    None
14    human_reference_2           geval_usefulness   error       NaN    None
15  raw_deepseek_v4_pro      deepeval_faithfulness  scored  1.000000    True
16  raw_deepseek_v4_pro            geval_coherence  scored  1.000000    True
17  raw_deepseek_v4_pro  geval_factual_correctness  scored  1.000000    True
18  raw_deepseek_v4_pro       geval_task_relevance  scored  0.800000    True
19  raw_deepseek_v4_pro           geval_usefulness  scored  0.700000    True

In [ ]:
import json
import re
import time
from datetime import datetime
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
    score_deepeval_for_notebook,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

# =========================
# Config
# =========================

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

DATASETS = [
    "dart",
]

START_INDEX = 0
EXAMPLES_PER_DATASET = 5

RAW_BASELINE_MODEL = "deepseek-v4-flash"

RUN_REFERENCE_METRICS = True
RUN_SOURCE_GROUNDED_METRICS = True
RUN_DEEPEVAL = True   # Set False if you want a faster run first.

DEEPEVAL_REPETITIONS = 1
DEEPEVAL_JUDGE_MODEL = "deepseek-v4-pro"

run_tag = datetime.now().strftime("%Y%m%d_%H%M%S")
experiment_name = f"five_dataset_five_each_comparison_{run_tag}"

# =========================
# Helpers
# =========================

def log(message):
    now = datetime.now().strftime("%H:%M:%S")
    print(f"[{now}] {message}", flush=True)

def safe_name(value):
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(value))

def write_json(path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))

def write_generation_records(path, records):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")

def show_report(title, text):
    display(Markdown(f"## {title}\n\n{text if str(text).strip() else '*No generated text.*'}"))

def compact_metric_table(scores):
    if scores.empty:
        return pd.DataFrame()

    return (
        scores[scores["status"].isin(["scored", "error", "skipped", "unavailable"])]
        .pivot_table(
            index=["dataset_id", "example_id", "metric_name"],
            columns="variant_id",
            values="score",
            aggfunc="first",
        )
        .reset_index()
    )

# =========================
# Build variants
# =========================

default_variants = load_json(paths["variant_config"])["variants"]

full_system_variant = next(
    variant for variant in default_variants
    if variant["variant_id"] == "full_system"
)

full_system_variant = {
    **full_system_variant,
    "enabled": True,
}

raw_variant = {
    "variant_id": f"raw_{RAW_BASELINE_MODEL.replace('-', '_')}",
    "enabled": True,
    "backend": "callable",
    "description": "Raw single-LLM DeepSeek baseline from source data only.",
    "settings_overrides": {
        "raw_baseline_model": RAW_BASELINE_MODEL,
        "raw_baseline_max_source_characters": 100000,
        "raw_baseline_max_output_tokens": 3000,
        "raw_baseline_temperature": 0.2,
    },
    "callable_path": "table2text.evaluation_backends.single_agent_baseline",
    "command": [],
    "precomputed_path": None,
    "repetitions": 1,
    "seeds": [42],
}

# =========================
# Metric configs
# =========================

base_metrics = load_json(paths["metric_config"])

reference_metrics_payload = base_metrics | {
    "baseline_variant": raw_variant["variant_id"],
}

reference_metrics_payload["deepeval"] = {
    **reference_metrics_payload["deepeval"],
    "judge_model": DEEPEVAL_JUDGE_MODEL,
    "judge_repetitions": DEEPEVAL_REPETITIONS,
}

source_metrics_payload = json.loads(json.dumps(reference_metrics_payload))
source_metrics_payload["reference_metrics"]["external_factuality_context"] = "source_text"
source_metrics_payload["reference_metrics"]["enabled_metrics"] = [
    "hhem",
    "alignscore",
]
source_metrics_payload["deepeval"] = {
    **source_metrics_payload["deepeval"],
    "run_summarization": False,
    "run_reference_adequacy": False,
}

reference_metrics_path = project_dir / f"evaluation/config/metrics_{experiment_name}_reference.json"
source_metrics_path = project_dir / f"evaluation/config/metrics_{experiment_name}_source_grounded.json"

write_json(reference_metrics_path, reference_metrics_payload)
write_json(source_metrics_path, source_metrics_payload)

# =========================
# Select 5 examples each
# =========================

all_examples = read_examples(paths["prepared_examples"])

selected_by_dataset = {}

for dataset_id in DATASETS:
    dataset_examples = [e for e in all_examples if e.dataset_id == dataset_id]

    if not dataset_examples:
        raise ValueError(f"No prepared examples found for dataset: {dataset_id}")

    selected = dataset_examples[START_INDEX : START_INDEX + EXAMPLES_PER_DATASET]

    if len(selected) < EXAMPLES_PER_DATASET:
        raise ValueError(
            f"Only found {len(selected)} examples for {dataset_id}, "
            f"but requested {EXAMPLES_PER_DATASET}."
        )

    selected_by_dataset[dataset_id] = selected

log(f"Experiment: {experiment_name}")
log(f"Datasets: {DATASETS}")
log(f"Examples per dataset: {EXAMPLES_PER_DATASET}")
log(f"Raw baseline: {RAW_BASELINE_MODEL}")
log(f"DeepEval: {RUN_DEEPEVAL}, judge={DEEPEVAL_JUDGE_MODEL}, reps={DEEPEVAL_REPETITIONS}")

# =========================
# Run dataset-by-dataset
# =========================

all_generation_records = []
all_reference_scores = []
all_source_scores = []
all_deepeval_scores = []

for dataset_number, dataset_id in enumerate(DATASETS, start=1):
    examples = selected_by_dataset[dataset_id]

    log("=" * 80)
    log(f"DATASET {dataset_number}/{len(DATASETS)}: {dataset_id}")
    log(f"Selected examples: {[e.example_id for e in examples]}")

    examples_path = project_dir / f"evaluation/prepared/{experiment_name}_{dataset_id}_five.jsonl"
    write_jsonl(examples_path, examples)

    dataset_generation_records = []

    for variant in [full_system_variant, raw_variant]:
        variant_id = variant["variant_id"]

        log("-" * 80)
        log(f"Starting generation: dataset={dataset_id}, variant={variant_id}, count={len(examples)}")

        single_variant_path = (
            project_dir
            / f"evaluation/config/variants_{experiment_name}_{dataset_id}_{variant_id}.json"
        )
        write_json(single_variant_path, {"variants": [variant]})

        variant_generations_path = (
            project_dir
            / f"evaluation/generations/{experiment_name}_{dataset_id}_{variant_id}_generations.jsonl"
        )
        run_root = (
            project_dir
            / f"evaluation/generations/{experiment_name}_runs/{dataset_id}/{variant_id}"
        )

        t0 = time.perf_counter()

        generation_frame = await generate_reports_for_notebook(
            project_dir,
            examples_path=examples_path,
            variants_path=single_variant_path,
            output_path=variant_generations_path,
            run_root=run_root,
            resume=False,
        )

        elapsed = time.perf_counter() - t0
        records = generation_frame.to_dict("records")

        dataset_generation_records.extend(records)
        all_generation_records.extend(records)

        log(
            f"Finished generation: dataset={dataset_id}, variant={variant_id}, "
            f"elapsed={elapsed:.1f}s, rows={len(records)}"
        )

        display(
            generation_frame[
                [
                    "dataset_id",
                    "example_id",
                    "variant_id",
                    "error",
                    "release_status",
                    "writer_mode",
                    "elapsed_seconds",
                ]
            ]
        )

        for row in records:
            log(
                f"Generated report: dataset={row.get('dataset_id')}, "
                f"example={row.get('example_id')}, variant={row.get('variant_id')}, "
                f"error={row.get('error')}"
            )
            show_report(
                f"{row.get('dataset_id')} / {row.get('example_id')} / {row.get('variant_id')}",
                row.get("generated_text") or "",
            )

    # Combined generation file for this dataset.
    dataset_generations_path = (
        project_dir
        / f"evaluation/generations/{experiment_name}_{dataset_id}_combined_generations.jsonl"
    )
    write_generation_records(dataset_generations_path, dataset_generation_records)

    log(f"Wrote combined dataset generations: {dataset_generations_path}")

    # =========================
    # Metrics for this dataset
    # =========================

    if RUN_REFERENCE_METRICS:
        log(f"Starting reference metrics for {dataset_id}")

        reference_scores_path = (
            project_dir
            / f"evaluation/results/{experiment_name}_{dataset_id}_reference_metrics.jsonl"
        )

        t0 = time.perf_counter()
        reference_scores = score_reference_metrics_for_notebook(
            project_dir,
            generations_path=dataset_generations_path,
            metric_config_path=reference_metrics_path,
            output_path=reference_scores_path,
            include_ineligible=True,
        )
        log(f"Finished reference metrics for {dataset_id} in {time.perf_counter() - t0:.1f}s")

        all_reference_scores.append(reference_scores)

        print(f"\nREFERENCE METRICS: {dataset_id}")
        display(compact_metric_table(reference_scores))

    if RUN_SOURCE_GROUNDED_METRICS:
        log(f"Starting source-grounded HHEM/AlignScore metrics for {dataset_id}")

        source_scores_path = (
            project_dir
            / f"evaluation/results/{experiment_name}_{dataset_id}_source_grounded_metrics.jsonl"
        )

        t0 = time.perf_counter()
        source_scores = score_reference_metrics_for_notebook(
            project_dir,
            generations_path=dataset_generations_path,
            metric_config_path=source_metrics_path,
            output_path=source_scores_path,
            include_ineligible=True,
        )
        log(f"Finished source-grounded metrics for {dataset_id} in {time.perf_counter() - t0:.1f}s")

        all_source_scores.append(source_scores)

        print(f"\nSOURCE-GROUNDED METRICS: {dataset_id}")
        display(compact_metric_table(source_scores))

    if RUN_DEEPEVAL:
        log(f"Starting DeepEval metrics for {dataset_id}. This can be slow.")

        deepeval_scores_path = (
            project_dir
            / f"evaluation/results/{experiment_name}_{dataset_id}_deepeval_metrics.jsonl"
        )

        t0 = time.perf_counter()
        deepeval_scores = score_deepeval_for_notebook(
            project_dir,
            generations_path=dataset_generations_path,
            metric_config_path=source_metrics_path,
            output_path=deepeval_scores_path,
            resume=False,
        )
        log(f"Finished DeepEval metrics for {dataset_id} in {time.perf_counter() - t0:.1f}s")

        all_deepeval_scores.append(deepeval_scores)

        print(f"\nDEEPEVAL METRICS: {dataset_id}")
        display(compact_metric_table(deepeval_scores))

# =========================
# Write combined files
# =========================

combined_generations_path = (
    project_dir
    / f"evaluation/generations/{experiment_name}_ALL_generations.jsonl"
)
write_generation_records(combined_generations_path, all_generation_records)

log("=" * 80)
log("ALL DATASETS COMPLETE")
log(f"Combined generations: {combined_generations_path}")
log(f"Reference metrics config: {reference_metrics_path}")
log(f"Source-grounded metrics config: {source_metrics_path}")

generations_all = pd.DataFrame(all_generation_records)

reference_all = (
    pd.concat(all_reference_scores, ignore_index=True)
    if all_reference_scores
    else pd.DataFrame()
)

source_all = (
    pd.concat(all_source_scores, ignore_index=True)
    if all_source_scores
    else pd.DataFrame()
)

deepeval_all = (
    pd.concat(all_deepeval_scores, ignore_index=True)
    if all_deepeval_scores
    else pd.DataFrame()
)

print("\nALL GENERATIONS")
display(
    generations_all[
        [
            "dataset_id",
            "example_id",
            "variant_id",
            "error",
            "release_status",
            "writer_mode",
            "elapsed_seconds",
        ]
    ]
)

print("\nALL REFERENCE METRICS")
display(compact_metric_table(reference_all))

print("\nALL SOURCE-GROUNDED METRICS")
display(compact_metric_table(source_all))

print("\nALL DEEPEVAL METRICS")
display(compact_metric_table(deepeval_all))

[23:33:48] Experiment: five_dataset_five_each_comparison_20260804_233348
[23:33:48] Datasets: ['dart']
[23:33:48] Examples per dataset: 5
[23:33:48] Raw baseline: deepseek-v4-flash
[23:33:48] DeepEval: True, judge=deepseek-v4-pro, reps=1
[23:33:48] ================================================================================
[23:33:48] DATASET 1/1: dart
[23:33:48] Selected examples: ['dart-test-53', 'dart-test-204', 'dart-test-217', 'dart-test-244', 'dart-test-260']
[23:33:48] --------------------------------------------------------------------------------
[23:33:48] Starting generation: dataset=dart, variant=full_system, count=5
[23:34:46] Finished generation: dataset=dart, variant=full_system, elapsed=58.2s, rows=5

,dataset_id,example_id,variant_id,error,release_status,writer_mode,elapsed_seconds
0,dart,dart-test-204,full_system,None,approved_with_warnings,llm_writer,8.242919
1,dart,dart-test-217,full_system,None,approved_with_warnings,llm_writer,8.821783
2,dart,dart-test-244,full_system,None,approved_with_warnings,llm_writer,18.617168
3,dart,dart-test-260,full_system,None,approved_with_warnings,llm_writer,12.392829
4,dart,dart-test-53,full_system,None,approved_with_warnings,llm_writer,10.102331

[23:34:46] Generated report: dataset=dart, example=dart-test-204, variant=full_system, error=None

## dart / dart-test-204 / full_system

AC Express has train number 22475/22476.

[23:34:46] Generated report: dataset=dart, example=dart-test-217, variant=full_system, error=None

## dart / dart-test-217 / full_system

Alabama 5's incumbent is Albert Rains.

[23:34:46] Generated report: dataset=dart, example=dart-test-244, variant=full_system, error=None

## dart / dart-test-244 / full_system

Piece of my heart is directed by Mark Tinker.

[23:34:46] Generated report: dataset=dart, example=dart-test-260, variant=full_system, error=None

## dart / dart-test-260 / full_system

Philippe Jeannol played from 1984 - 1991 and made 219 appearances¹.

[23:34:46] Generated report: dataset=dart, example=dart-test-53, variant=full_system, error=None

## dart / dart-test-53 / full_system

University of Makati UM Pep Squad recorded a total of 211.5 and ranked 11th.

[23:34:46] --------------------------------------------------------------------------------
[23:34:46] Starting generation: dataset=dart, variant=raw_deepseek_v4_flash, count=5
[23:34:54] Finished generation: dataset=dart, variant=raw_deepseek_v4_flash, elapsed=7.9s, rows=5

,dataset_id,example_id,variant_id,error,release_status,writer_mode,elapsed_seconds
0,dart,dart-test-204,raw_deepseek_v4_flash,None,None,None,1.793034
1,dart,dart-test-217,raw_deepseek_v4_flash,None,None,None,1.608583
2,dart,dart-test-244,raw_deepseek_v4_flash,None,None,None,1.329972
3,dart,dart-test-260,raw_deepseek_v4_flash,None,None,None,1.880485
4,dart,dart-test-53,raw_deepseek_v4_flash,None,None,None,1.247942

[23:34:54] Generated report: dataset=dart, example=dart-test-204, variant=raw_deepseek_v4_flash, error=None

## dart / dart-test-204 / raw_deepseek_v4_flash

The train number of AC Express is 22475/22476.

[23:34:54] Generated report: dataset=dart, example=dart-test-217, variant=raw_deepseek_v4_flash, error=None

## dart / dart-test-217 / raw_deepseek_v4_flash

The incumbent of Alabama 5 is Albert Rains.

[23:34:54] Generated report: dataset=dart, example=dart-test-244, variant=raw_deepseek_v4_flash, error=None

## dart / dart-test-244 / raw_deepseek_v4_flash

Piece of My Heart was directed by Mark Tinker.

[23:34:54] Generated report: dataset=dart, example=dart-test-260, variant=raw_deepseek_v4_flash, error=None

## dart / dart-test-260 / raw_deepseek_v4_flash

Philippe Jeannol's period was 1984–1991, with 219 appearances.

[23:34:54] Generated report: dataset=dart, example=dart-test-53, variant=raw_deepseek_v4_flash, error=None

## dart / dart-test-53 / raw_deepseek_v4_flash

The University of Makati UM Pep Squad scored a total of 211.5 and ranked 11th.

[23:34:54] Wrote combined dataset generations: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/five_dataset_five_each_comparison_20260804_233348_dart_combined_generations.jsonl
[23:34:54] Starting reference metrics for dart

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
You are using a model of type HHEMv2Config to instantiate a model of type HHEMv2. This is not supported for all configurations of models and can yield errors.
Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[23:35:12] Finished reference metrics for dart in 18.4s

REFERENCE METRICS: dart

variant_id,dataset_id,example_id,metric_name,full_system,raw_deepseek_v4_flash
0,dart,dart-test-204,alignscore_base,0.828803,0.749153
1,dart,dart-test-204,bertscore_f1,0.965391,0.964035
2,dart,dart-test-204,bleu,0.354948,0.350844
3,dart,dart-test-204,chrf,0.580213,0.673405
4,dart,dart-test-204,corpus_bleu,0.219679,0.195801
...,...,...,...,...,...
63,dart,dart-test-53,rouge1,0.583333,0.560000
64,dart,dart-test-53,rouge2,0.454545,0.434783
65,dart,dart-test-53,rougeL,0.416667,0.400000
66,dart,dart-test-53,rougeLsum,0.416667,0.400000
67,dart,dart-test-53,ter,1.250000,1.375000

[23:35:12] Starting source-grounded HHEM/AlignScore metrics for dart

You are using a model of type HHEMv2Config to instantiate a model of type HHEMv2. This is not supported for all configurations of models and can yield errors.

[23:35:24] Finished source-grounded metrics for dart in 12.3s

SOURCE-GROUNDED METRICS: dart

variant_id,dataset_id,example_id,metric_name,full_system,raw_deepseek_v4_flash
0,dart,dart-test-204,alignscore_base,0.984554,0.987814
1,dart,dart-test-204,hhem_2_1_open_mean_support,0.975844,0.950525
2,dart,dart-test-204,hhem_2_1_open_min_sentence_support,0.975844,0.950525
3,dart,dart-test-204,hhem_2_1_open_unsupported_sentence_rate,0.000000,0.000000
4,dart,dart-test-217,alignscore_base,0.952588,0.956444
5,dart,dart-test-217,hhem_2_1_open_mean_support,0.917543,0.911588
6,dart,dart-test-217,hhem_2_1_open_min_sentence_support,0.917543,0.911588
7,dart,dart-test-217,hhem_2_1_open_unsupported_sentence_rate,0.000000,0.000000
8,dart,dart-test-244,alignscore_base,0.990330,0.990098
9,dart,dart-test-244,hhem_2_1_open_mean_support,0.930509,0.932231
10,dart,dart-test-244,hhem_2_1_open_min_sentence_support,0.930509,0.932231
11,dart,dart-test-244,hhem_2_1_open_unsupported_sentence_rate,0.000000,0.000000
12,dart,dart-test-260,alignscore_base,0.974583,0.968514
13,dart,dart-test-260,hhem_2_1_open_mean_support,0.792125,0.744518
14,dart,dart-test-260,hhem_2_1_open_min_sentence_support,0.792125,0.744518
15,dart,dart-test-260,hhem_2_1_open_unsupported_sentence_rate,0.000000,0.000000
16,dart,dart-test-53,alignscore_base,0.984827,0.990027
17,dart,dart-test-53,hhem_2_1_open_mean_support,0.766980,0.735886
18,dart,dart-test-53,hhem_2_1_open_min_sentence_support,0.766980,0.735886
19,dart,dart-test-53,hhem_2_1_open_unsupported_sentence_rate,0.000000,0.000000

[23:35:24] Starting DeepEval metrics for dart. This can be slow.

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/rich/live.py:260:
UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

In [1]:
import json
import os
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
    load_project_env,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)
load_project_env(project_dir)

dataset_id = "sportsett_basketball"
example_id = "4934"

examples = read_examples(paths["prepared_examples"])
one_example = next(
    e for e in examples
    if e.dataset_id == dataset_id and str(e.example_id) == example_id
)

examples_path = project_dir / f"evaluation/prepared/{dataset_id}_{example_id}_fast_compare.jsonl"
write_jsonl(examples_path, [one_example])

variants = {
    "variants": [
        {
            "variant_id": "full_system_fast",
            "enabled": True,
            "backend": "table2text",
            "description": "Fast full-system run using .env flash routing.",
            "settings_overrides": {
                "use_llm": True,
                "structured_output_mode": "prompted",
                "max_total_tokens": 300000,
                "max_agent_requests": 5,
                "max_revision_rounds": 0,
                "writer_quality_revision_rounds": 0,
                "enable_insight_synthesis": True,
            },
            "callable_path": None,
            "command": [],
            "precomputed_path": None,
            "repetitions": 1,
            "seeds": [42],
        },
        {
            "variant_id": "raw_deepseek_v4_pro",
            "enabled": True,
            "backend": "callable",
            "description": "Raw one-shot DeepSeek v4-pro baseline.",
            "settings_overrides": {
                "raw_baseline_model": "deepseek-v4-pro",
                "raw_baseline_max_source_characters": 100000,
                "raw_baseline_max_output_tokens": 3000,
                "raw_baseline_temperature": 0.2,
            },
            "callable_path": "table2text.evaluation_backends.single_agent_baseline",
            "command": [],
            "precomputed_path": None,
            "repetitions": 1,
            "seeds": [42],
        },
    ]
}

variants_path = project_dir / f"evaluation/config/variants_{dataset_id}_{example_id}_fast_compare.json"
variants_path.write_text(json.dumps(variants, indent=2), encoding="utf-8")

generations_path = project_dir / f"evaluation/generations/{dataset_id}_{example_id}_fast_compare_generations.jsonl"
run_root = project_dir / f"evaluation/generations/{dataset_id}_{example_id}_fast_compare_runs"

print("Model routing from .env:")
for key in [
    "T2T_MODEL_DATA_UNDERSTANDING",
    "T2T_MODEL_ORCHESTRATOR",
    "T2T_MODEL_EVIDENCE",
    "T2T_MODEL_VERIFIER",
    "T2T_MODEL_WRITER",
    "T2T_MODEL_AUDITOR",
]:
    print(f"{key} = {os.getenv(key)}")

print("\nGenerating full system + raw baseline...")
generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=generations_path,
    run_root=run_root,
    resume=False,
)

for _, row in generations.iterrows():
    print("\n" + "=" * 80)
    print("Variant:", row["variant_id"])
    print("Error:", row["error"])
    print("Release status:", row.get("release_status"))
    print("Writer mode:", row.get("writer_mode"))
    print("Elapsed seconds:", row.get("elapsed_seconds"))
    print("Artifact:", row.get("pipeline_result_path"))
    print("-" * 80)
    print(row["generated_text"])

# Reference metrics only. No DeepEval.
metrics_path = project_dir / f"evaluation/config/metrics_{dataset_id}_{example_id}_fast_reference_only.json"

metrics_config = {
    "experiment_id": f"{dataset_id}_{example_id}_fast_reference_only",
    "baseline_variant": "raw_deepseek_v4_pro",
    "reference_metrics": {
        "run_bleu": True,
        "run_chrf": True,
        "run_ter": True,
        "run_rouge": True,
        "run_meteor": True,
        "run_bertscore": True,
        "run_parent": True,
        "run_hhem": False,
        "run_alignscore": False,
    },
    "deepeval": {
        "enabled": False,
    },
}
metrics_path.write_text(json.dumps(metrics_config, indent=2), encoding="utf-8")

print("\nScoring reference metrics...")
scores_path = project_dir / f"evaluation/results/{dataset_id}_{example_id}_fast_reference_metrics.jsonl"

scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=generations_path,
    metric_config_path=metrics_path,
    output_path=scores_path,
)

print("\nMetric comparison:")
comparison = (
    scores[
        scores["status"].eq("scored")
        & scores["variant_id"].isin(["full_system_fast", "raw_deepseek_v4_flash"])
    ]
    .pivot_table(
        index="metric_name",
        columns="variant_id",
        values="score",
        aggfunc="mean",
    )
    .reset_index()
)

if {"full_system_fast", "raw_deepseek_v4_flash"}.issubset(comparison.columns):
    comparison["delta_system_minus_raw"] = (
        comparison["full_system_fast"] - comparison["raw_deepseek_v4_flash"]
    )

display(comparison)

print("\nGenerations saved to:", generations_path)
print("Metrics saved to:", scores_path)

generations[
    [
        "dataset_id",
        "example_id",
        "variant_id",
        "generated_text",
        "error",
        "release_status",
        "writer_mode",
        "elapsed_seconds",
        "pipeline_result_path",
    ]
]

Model routing from .env:
T2T_MODEL_DATA_UNDERSTANDING = deepseek:deepseek-v4-pro
T2T_MODEL_ORCHESTRATOR = deepseek:deepseek-v4-pro
T2T_MODEL_EVIDENCE = deepseek:deepseek-v4-pro
T2T_MODEL_VERIFIER = deepseek:deepseek-v4-pro
T2T_MODEL_WRITER = deepseek:deepseek-v4-pro
T2T_MODEL_AUDITOR = deepseek:deepseek-v4-pro

Generating full system + raw baseline...

================================================================================
Variant: full_system_fast
Error: None
Release status: approved_with_warnings
Writer mode: llm_writer
Elapsed seconds: 1082.6152862500167
Artifact: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/sportsett_basketball_4934_fast_compare_runs/full_system_fast/sportsett_basketball/20260811T202300Z_6fbc97c364/pipeline_result.json
--------------------------------------------------------------------------------
The Philadelphia 76ers defeated the Memphis Grizzlies 103-95 on Sunday, December 2, 2018 at Wells Fargo Center, leading at the end of every quarter.
Philadelphia, third in the Eastern Conference, entered the game with a 17-8 record, while Memphis, sixth in the Western Conference, held a 13-9 mark.
It was the 76ers' 25th game of the season and the Grizzlies' 22nd.
After a tight first quarter that saw Philadelphia edge ahead 26-25, the 76ers pulled away in the second, outscoring the Grizzlies 28-19 to take a commanding 54-44 lead into halftime.
The third quarter was evenly matched at 24-24, and though Memphis won the fourth 27-25, Philadelphia’s cushion proved sufficient to secure the hard-earned 103-95 victory.
The 76ers had a balanced attack with three players scoring at least 19 points, while the Grizzlies relied on Mike Conley (21 points) and Jaren Jackson (17 points) for most of their offense.
J.J. Redick led all scorers with 24 points, and Jimmy Butler added 21.
Ben Simmons recorded 19 points, a team-high six assists, and grabbed 10 defensive and 2 offensive rebounds, while Joel Embiid anchored the defense with 14 defensive rebounds, 15 points and three assists.
For Memphis, Mike Conley matched Butler with 21 points and five assists, Jaren Jackson added 17 points, and JaMychal Green contributed 14 points and five defensive rebounds.
Kyle Anderson added five assists and five points, and the Grizzlies got 12 points each from Marc Gasol, Garrett Temple and MarShon Brooks.
The 76ers now travel to Toronto for a Wednesday night matchup with the Raptors at Scotiabank Arena, while the Grizzlies return to Memphis to host the Los Angeles Clippers at FedExForum the same Wednesday night.


================================================================================
Variant: raw_deepseek_v4_pro
Error: None
Release status: None
Writer mode: None
Elapsed seconds: 21.599349166965112
Artifact: None
--------------------------------------------------------------------------------
The Philadelphia 76ers defeated the Memphis Grizzlies 103-95 on Sunday at a sold-out Wells Fargo Center, improving to 17-8 on the season while Memphis dropped to 13-9. Philadelphia built a decisive advantage in the second quarter and never trailed over the final three periods.

J.J. Redick led all scorers with 24 points, connecting on 9-of-17 from the field, including three three-pointers. Jimmy Butler added 21 points, and Ben Simmons notched a double-double with 19 points on an efficient 8-of-10 shooting and 12 rebounds, along with six assists. Joel Embiid also recorded a double-double, contributing 15 points and a game-high 14 rebounds despite a 4-of-13 shooting night. Mike Muscala chipped in eight points and seven rebounds for the 76ers, who shot 49 percent overall and went 23-of-30 from the free-throw line.

Memphis kept it close in the opening frame, trailing just 26-25, but managed only 19 points in the second quarter as Philadelphia surged to a 54-44 halftime lead. Mike Conley paced the Grizzlies with 21 points and five assists, while Jaren Jackson totaled 17 points and went a perfect 6-of-6 from the stripe. Reserve JaMychal Green provided a spark off the bench with 14 points and seven rebounds, and MarShon Brooks scored 12 points. Marc Gasol finished with 12 points but shot 4-of-14 from the floor. The Grizzlies outscored the 76ers 27-25 in the fourth but never seriously threatened, as Philadelphia controlled the glass with a 44-35 rebounding edge and forced 14 turnovers while committing 16.

Scoring reference metrics...

ValidationError: 11 validation errors for ExperimentConfig
prepared_examples_path
  Field required [type=missing, input_value={'experiment_id': 'sports...al': {'enabled': False}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
generations_path
  Field required [type=missing, input_value={'experiment_id': 'sports...al': {'enabled': False}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.13/v/missing
reference_metrics.run_bleu
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden
reference_metrics.run_chrf
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden
reference_metrics.run_ter
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden
reference_metrics.run_rouge
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden
reference_metrics.run_meteor
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden
reference_metrics.run_bertscore
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden
reference_metrics.run_parent
  Extra inputs are not permitted [type=extra_forbidden, input_value=True, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden
reference_metrics.run_hhem
  Extra inputs are not permitted [type=extra_forbidden, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden
reference_metrics.run_alignscore
  Extra inputs are not permitted [type=extra_forbidden, input_value=False, input_type=bool]
    For further information visit https://errors.pydantic.dev/2.13/v/extra_forbidden

In [4]:
import json
import time
from datetime import datetime
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
    load_project_env,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)
load_project_env(project_dir)

DATASETS = ["e2e_nlg", "totto", "web_nlg", "dart"]
START_INDEX = 0

run_tag = datetime.now().strftime("%Y%m%d_%H%M%S")
experiment_name = f"four_dataset_pro_comparison_{run_tag}"

def log(msg):
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)

def write_json(path, payload):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

def write_generation_records(path, records):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")

def show_report(title, text):
    display(Markdown(f"## {title}\n\n{text if str(text).strip() else '*No generated text.*'}"))

def compact_metric_table(scores):
    if scores.empty:
        return pd.DataFrame()

    return (
        scores[scores["status"].eq("scored")]
        .pivot_table(
            index=["dataset_id", "example_id", "metric_name"],
            columns="variant_id",
            values="score",
            aggfunc="first",
        )
        .reset_index()
    )

examples = read_examples(paths["prepared_examples"])

selected_examples = []
for dataset_id in DATASETS:
    dataset_examples = [e for e in examples if e.dataset_id == dataset_id]
    if not dataset_examples:
        raise ValueError(f"No prepared examples found for {dataset_id}")
    selected_examples.append(dataset_examples[START_INDEX])

full_system_pro = {
    "variant_id": "full_system_pro",
    "enabled": True,
    "backend": "table2text",
    "description": "Full Table2Text workflow with all agents on DeepSeek v4-pro.",
    "settings_overrides": {
        "use_llm": True,
        "structured_output_mode": "prompted",
        "max_total_tokens": 300000,
        "max_agent_requests": 8,

        "data_understanding_model": "deepseek:deepseek-v4-pro",
        "orchestrator_model": "deepseek:deepseek-v4-pro",
        "evidence_model": "deepseek:deepseek-v4-pro",
        "verifier_model": "deepseek:deepseek-v4-pro",
        "writer_model": "deepseek:deepseek-v4-pro",
        "auditor_model": "deepseek:deepseek-v4-pro",
    },
    "callable_path": None,
    "command": [],
    "precomputed_path": None,
    "repetitions": 1,
    "seeds": [42],
}

raw_generic_pro = {
    "variant_id": "raw_generic_pro",
    "enabled": True,
    "backend": "callable",
    "description": "Raw generic one-shot DeepSeek v4-pro baseline.",
    "settings_overrides": {
        "raw_baseline_model": "deepseek-v4-pro",
        "raw_baseline_prompt_mode": "generic",
        "raw_baseline_max_source_characters": 100000,
        "raw_baseline_max_output_tokens": 3000,
        "raw_baseline_temperature": 0.2,
    },
    "callable_path": "table2text.evaluation_backends.single_agent_baseline",
    "command": [],
    "precomputed_path": None,
    "repetitions": 1,
    "seeds": [42],
}

variants_path = project_dir / f"evaluation/config/variants_{experiment_name}.json"
write_json(variants_path, {"variants": [full_system_pro, raw_generic_pro]})

base_metrics = json.loads(paths["metric_config"].read_text(encoding="utf-8"))
metrics_config = {
    **base_metrics,
    "experiment_id": experiment_name,
    "prepared_examples_path": str(paths["prepared_examples"]),
    "generations_path": str(
        project_dir / f"evaluation/generations/{experiment_name}_combined_generations.jsonl"
    ),
    "baseline_variant": "raw_generic_pro",
}
metrics_config["reference_metrics"]["enabled_metrics"] = [
    "bleu",
    "chrf",
    "ter",
    "rouge1",
    "rouge2",
    "rougeL",
    "rougeLsum",
    "meteor",
    "bertscore",
]
metrics_config["deepeval"]["enabled"] = False

metrics_path = project_dir / f"evaluation/config/metrics_{experiment_name}.json"
write_json(metrics_path, metrics_config)

all_generation_records = []
all_scores = []

log(f"Experiment: {experiment_name}")
log(f"Datasets: {DATASETS}")
log("Running full_system_pro vs raw_generic_pro")

for i, example in enumerate(selected_examples, start=1):
    dataset_id = example.dataset_id
    example_id = example.example_id

    log("=" * 80)
    log(f"Dataset {i}/{len(selected_examples)}: {dataset_id} / {example_id}")

    examples_path = project_dir / f"evaluation/prepared/{experiment_name}_{dataset_id}_{example_id}.jsonl"
    write_jsonl(examples_path, [example])

    dataset_generations_path = (
        project_dir / f"evaluation/generations/{experiment_name}_{dataset_id}_generations.jsonl"
    )
    run_root = project_dir / f"evaluation/generations/{experiment_name}_runs/{dataset_id}"

    t0 = time.perf_counter()
    generations = await generate_reports_for_notebook(
        project_dir,
        examples_path=examples_path,
        variants_path=variants_path,
        output_path=dataset_generations_path,
        run_root=run_root,
        resume=False,
    )
    log(f"Generated {dataset_id} in {time.perf_counter() - t0:.1f}s")

    records = generations.to_dict("records")
    all_generation_records.extend(records)

    for _, row in generations.iterrows():
        log(
            f"{row['variant_id']}: error={row.get('error')}, "
            f"release={row.get('release_status')}, "
            f"writer={row.get('writer_mode')}, "
            f"elapsed={row.get('elapsed_seconds')}"
        )
        show_report(
            f"{dataset_id} / {example_id} / {row['variant_id']}",
            row.get("generated_text") or "",
        )

    scores_path = project_dir / f"evaluation/results/{experiment_name}_{dataset_id}_reference_metrics.jsonl"
    scores = score_reference_metrics_for_notebook(
        project_dir,
        generations_path=dataset_generations_path,
        metric_config_path=metrics_path,
        output_path=scores_path,
        include_ineligible=True,
    )
    all_scores.append(scores)

    print(f"\nMETRICS: {dataset_id}")
    display(compact_metric_table(scores))

combined_generations_path = project_dir / f"evaluation/generations/{experiment_name}_combined_generations.jsonl"
write_generation_records(combined_generations_path, all_generation_records)

combined_scores = pd.concat(all_scores, ignore_index=True) if all_scores else pd.DataFrame()
combined_scores_path = project_dir / f"evaluation/results/{experiment_name}_reference_metrics_combined.jsonl"

with combined_scores_path.open("w", encoding="utf-8") as handle:
    for record in combined_scores.to_dict("records"):
        handle.write(json.dumps(record, ensure_ascii=False) + "\n")

print("\nALL DONE")
print("Combined generations:", combined_generations_path)
print("Combined metrics:", combined_scores_path)

print("\nGENERATION SUMMARY")
display(
    pd.DataFrame(all_generation_records)[
        [
            "dataset_id",
            "example_id",
            "variant_id",
            "error",
            "release_status",
            "writer_mode",
            "elapsed_seconds",
        ]
    ]
)

print("\nCOMBINED METRICS")
display(compact_metric_table(combined_scores))

[21:52:39] Experiment: four_dataset_pro_comparison_20260812_215239
[21:52:39] Datasets: ['e2e_nlg', 'totto', 'web_nlg', 'dart']
[21:52:39] Running full_system_pro vs raw_generic_pro
[21:52:39] ================================================================================
[21:52:39] Dataset 1/4: e2e_nlg / e2e_nlg-test-51
[21:53:02] Generated e2e_nlg in 23.3s
[21:53:02] full_system_pro: error=None, release=approved_with_warnings, writer=llm_writer, elapsed=20.936403250088915

## e2e_nlg / e2e_nlg-test-51 / full_system_pro

Clowns is a pub near Crowne Plaza Hotel and has a customer rating of 5 out of 5.

[21:53:02] raw_generic_pro: error=None, release=None, writer=None, elapsed=2.325567915919237

## e2e_nlg / e2e_nlg-test-51 / raw_generic_pro

Clowns is a pub near Crowne Plaza Hotel with a customer rating of 5 out of 5.

Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

METRICS: e2e_nlg

variant_id,dataset_id,example_id,metric_name,full_system_pro,raw_generic_pro
0,e2e_nlg,e2e_nlg-test-51,bertscore_f1,0.977647,0.977839
1,e2e_nlg,e2e_nlg-test-51,bleu,0.907111,0.793805
2,e2e_nlg,e2e_nlg-test-51,chrf,0.885880,0.848314
3,e2e_nlg,e2e_nlg-test-51,corpus_bleu,0.907111,0.793805
4,e2e_nlg,e2e_nlg-test-51,corpus_chrf,0.885880,0.848314
5,e2e_nlg,e2e_nlg-test-51,corpus_ter,0.117647,0.176471
6,e2e_nlg,e2e_nlg-test-51,meteor,0.941849,0.890909
7,e2e_nlg,e2e_nlg-test-51,rouge1,0.944444,0.971429
8,e2e_nlg,e2e_nlg-test-51,rouge2,0.823529,0.848485
9,e2e_nlg,e2e_nlg-test-51,rougeL,0.888889,0.800000
10,e2e_nlg,e2e_nlg-test-51,rougeLsum,0.888889,0.800000
11,e2e_nlg,e2e_nlg-test-51,ter,0.117647,0.176471

[21:53:03] ================================================================================
[21:53:03] Dataset 2/4: totto / totto-validation-204
[21:53:27] Generated totto in 23.2s
[21:53:27] full_system_pro: error=None, release=approved_with_warnings, writer=llm_writer, elapsed=19.349715000018477

## totto / totto-validation-204 / full_system_pro

Ma Ying-jeou received 58.45% of the vote.

[21:53:27] raw_generic_pro: error=None, release=None, writer=None, elapsed=3.826612417004071

## totto / totto-validation-204 / raw_generic_pro

The highlighted cell shows that Vincent Siew received 58.45% of the vote.

Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

METRICS: totto

variant_id,dataset_id,example_id,metric_name,full_system_pro,raw_generic_pro
0,totto,totto-validation-204,bertscore_f1,0.911496,0.907946
1,totto,totto-validation-204,bleu,0.488829,0.349876
2,totto,totto-validation-204,chrf,0.496636,0.450343
3,totto,totto-validation-204,corpus_bleu,0.488829,0.349876
4,totto,totto-validation-204,corpus_chrf,0.496636,0.450343
5,totto,totto-validation-204,corpus_ter,0.400000,0.800000
6,totto,totto-validation-204,meteor,0.550000,0.520430
7,totto,totto-validation-204,rouge1,0.631579,0.521739
8,totto,totto-validation-204,rouge2,0.470588,0.380952
9,totto,totto-validation-204,rougeL,0.631579,0.521739
10,totto,totto-validation-204,rougeLsum,0.631579,0.521739
11,totto,totto-validation-204,ter,0.400000,0.800000

[21:53:28] ================================================================================
[21:53:28] Dataset 3/4: web_nlg / web_nlg_en-test-51
[21:54:01] Generated web_nlg in 33.8s
[21:54:01] full_system_pro: error=None, release=approved_with_warnings, writer=llm_writer, elapsed=31.86485441599507

## web_nlg / web_nlg_en-test-51 / full_system_pro

ALCO_RS-3 has a Four-stroke engine, 12 cylinders, and a length of 17068.8 (millimetres).

[21:54:01] raw_generic_pro: error=None, release=None, writer=None, elapsed=1.9047611670102924

## web_nlg / web_nlg_en-test-51 / raw_generic_pro

The ALCO RS-3 is powered by a four-stroke engine, has 12 cylinders, and is 17,068.8 millimetres long.

Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

METRICS: web_nlg

variant_id,dataset_id,example_id,metric_name,full_system_pro,raw_generic_pro
0,web_nlg,web_nlg_en-test-51,bertscore_f1,0.952478,0.951219
1,web_nlg,web_nlg_en-test-51,bleu,0.257597,0.242180
2,web_nlg,web_nlg_en-test-51,chrf,0.631083,0.679644
3,web_nlg,web_nlg_en-test-51,corpus_bleu,0.257597,0.242180
4,web_nlg,web_nlg_en-test-51,corpus_chrf,0.631083,0.679644
5,web_nlg,web_nlg_en-test-51,corpus_ter,0.533333,0.666667
6,web_nlg,web_nlg_en-test-51,meteor,0.597134,0.589953
7,web_nlg,web_nlg_en-test-51,rouge1,0.944444,0.705882
8,web_nlg,web_nlg_en-test-51,rouge2,0.705882,0.437500
9,web_nlg,web_nlg_en-test-51,rougeL,0.833333,0.600000
10,web_nlg,web_nlg_en-test-51,rougeLsum,0.833333,0.600000
11,web_nlg,web_nlg_en-test-51,ter,0.533333,0.666667

[21:54:02] ================================================================================
[21:54:02] Dataset 4/4: dart / dart-test-53
[21:54:19] Generated dart in 16.5s
[21:54:19] full_system_pro: error=None, release=approved_with_warnings, writer=llm_writer, elapsed=14.460691791027784

## dart / dart-test-53 / full_system_pro

University of Makati UM Pep Squad has a total of 211.5 and ranks 11th.

[21:54:19] raw_generic_pro: error=None, release=None, writer=None, elapsed=1.9845748340012506

## dart / dart-test-53 / raw_generic_pro

The University of Makati UM Pep Squad has a total of 211.5 and ranks 11th.

Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

METRICS: dart

variant_id,dataset_id,example_id,metric_name,full_system_pro,raw_generic_pro
0,dart,dart-test-53,bertscore_f1,0.926383,0.915106
1,dart,dart-test-53,bleu,0.195648,0.182071
2,dart,dart-test-53,chrf,0.566182,0.555137
3,dart,dart-test-53,corpus_bleu,0.195648,0.182071
4,dart,dart-test-53,corpus_chrf,0.566182,0.555137
5,dart,dart-test-53,corpus_ter,1.250000,1.375000
6,dart,dart-test-53,meteor,0.562791,0.556322
7,dart,dart-test-53,rouge1,0.583333,0.560000
8,dart,dart-test-53,rouge2,0.454545,0.434783
9,dart,dart-test-53,rougeL,0.416667,0.400000
10,dart,dart-test-53,rougeLsum,0.416667,0.400000
11,dart,dart-test-53,ter,1.250000,1.375000

ALL DONE
Combined generations: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/four_dataset_pro_comparison_20260812_215239_combined_generations.jsonl
Combined metrics: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/four_dataset_pro_comparison_20260812_215239_reference_metrics_combined.jsonl

GENERATION SUMMARY

,dataset_id,example_id,variant_id,error,release_status,writer_mode,elapsed_seconds
0,e2e_nlg,e2e_nlg-test-51,full_system_pro,None,approved_with_warnings,llm_writer,20.936403
1,e2e_nlg,e2e_nlg-test-51,raw_generic_pro,None,None,None,2.325568
2,totto,totto-validation-204,full_system_pro,None,approved_with_warnings,llm_writer,19.349715
3,totto,totto-validation-204,raw_generic_pro,None,None,None,3.826612
4,web_nlg,web_nlg_en-test-51,full_system_pro,None,approved_with_warnings,llm_writer,31.864854
5,web_nlg,web_nlg_en-test-51,raw_generic_pro,None,None,None,1.904761
6,dart,dart-test-53,full_system_pro,None,approved_with_warnings,llm_writer,14.460692
7,dart,dart-test-53,raw_generic_pro,None,None,None,1.984575

COMBINED METRICS

variant_id,dataset_id,example_id,metric_name,full_system_pro,raw_generic_pro
0,dart,dart-test-53,bertscore_f1,0.926383,0.915106
1,dart,dart-test-53,bleu,0.195648,0.182071
2,dart,dart-test-53,chrf,0.566182,0.555137
3,dart,dart-test-53,corpus_bleu,0.195648,0.182071
4,dart,dart-test-53,corpus_chrf,0.566182,0.555137
5,dart,dart-test-53,corpus_ter,1.250000,1.375000
6,dart,dart-test-53,meteor,0.562791,0.556322
7,dart,dart-test-53,rouge1,0.583333,0.560000
8,dart,dart-test-53,rouge2,0.454545,0.434783
9,dart,dart-test-53,rougeL,0.416667,0.400000
10,dart,dart-test-53,rougeLsum,0.416667,0.400000
11,dart,dart-test-53,ter,1.250000,1.375000
12,e2e_nlg,e2e_nlg-test-51,bertscore_f1,0.977647,0.977839
13,e2e_nlg,e2e_nlg-test-51,bleu,0.907111,0.793805
14,e2e_nlg,e2e_nlg-test-51,chrf,0.885880,0.848314
15,e2e_nlg,e2e_nlg-test-51,corpus_bleu,0.907111,0.793805
16,e2e_nlg,e2e_nlg-test-51,corpus_chrf,0.885880,0.848314
17,e2e_nlg,e2e_nlg-test-51,corpus_ter,0.117647,0.176471
18,e2e_nlg,e2e_nlg-test-51,meteor,0.941849,0.890909
19,e2e_nlg,e2e_nlg-test-51,rouge1,0.944444,0.971429
20,e2e_nlg,e2e_nlg-test-51,rouge2,0.823529,0.848485
21,e2e_nlg,e2e_nlg-test-51,rougeL,0.888889,0.800000
22,e2e_nlg,e2e_nlg-test-51,rougeLsum,0.888889,0.800000
23,e2e_nlg,e2e_nlg-test-51,ter,0.117647,0.176471
24,totto,totto-validation-204,bertscore_f1,0.911496,0.907946
25,totto,totto-validation-204,bleu,0.488829,0.349876
26,totto,totto-validation-204,chrf,0.496636,0.450343
27,totto,totto-validation-204,corpus_bleu,0.488829,0.349876
28,totto,totto-validation-204,corpus_chrf,0.496636,0.450343
29,totto,totto-validation-204,corpus_ter,0.400000,0.800000
30,totto,totto-validation-204,meteor,0.550000,0.520430
31,totto,totto-validation-204,rouge1,0.631579,0.521739
32,totto,totto-validation-204,rouge2,0.470588,0.380952
33,totto,totto-validation-204,rougeL,0.631579,0.521739
34,totto,totto-validation-204,rougeLsum,0.631579,0.521739
35,totto,totto-validation-204,ter,0.400000,0.800000
36,web_nlg,web_nlg_en-test-51,bertscore_f1,0.952478,0.951219
37,web_nlg,web_nlg_en-test-51,bleu,0.257597,0.242180
38,web_nlg,web_nlg_en-test-51,chrf,0.631083,0.679644
39,web_nlg,web_nlg_en-test-51,corpus_bleu,0.257597,0.242180
40,web_nlg,web_nlg_en-test-51,corpus_chrf,0.631083,0.679644
41,web_nlg,web_nlg_en-test-51,corpus_ter,0.533333,0.666667
42,web_nlg,web_nlg_en-test-51,meteor,0.597134,0.589953
43,web_nlg,web_nlg_en-test-51,rouge1,0.944444,0.705882
44,web_nlg,web_nlg_en-test-51,rouge2,0.705882,0.437500
45,web_nlg,web_nlg_en-test-51,rougeL,0.833333,0.600000
46,web_nlg,web_nlg_en-test-51,rougeLsum,0.833333,0.600000
47,web_nlg,web_nlg_en-test-51,ter,0.533333,0.666667

In [3]:
import json
from pathlib import Path
from table2text.evaluation import default_paths, score_reference_metrics_for_notebook

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

dataset_id = "sportsett_basketball"
example_id = "4934"

generations_path = project_dir / f"evaluation/generations/{dataset_id}_{example_id}_fast_compare_generations.jsonl"
metrics_path = project_dir / f"evaluation/config/metrics_{dataset_id}_{example_id}_fast_reference_only_fixed.json"
scores_path = project_dir / f"evaluation/results/{dataset_id}_{example_id}_fast_reference_metrics_fixed.jsonl"

base_metrics = json.loads(paths["metric_config"].read_text(encoding="utf-8"))

metrics_config = {
    **base_metrics,
    "experiment_id": f"{dataset_id}_{example_id}_fast_reference_only_fixed",
    "prepared_examples_path": str(paths["prepared_examples"]),
    "generations_path": str(generations_path),
    "baseline_variant": "raw_deepseek_v4_pro",
}

metrics_config["reference_metrics"]["enabled_metrics"] = [
    "bleu",
    "chrf",
    "ter",
    "rouge1",
    "rouge2",
    "rougeL",
    "rougeLsum",
    "meteor",
    "bertscore",
]

metrics_config["deepeval"]["enabled"] = False

metrics_path.write_text(json.dumps(metrics_config, indent=2), encoding="utf-8")

scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=generations_path,
    metric_config_path=metrics_path,
    output_path=scores_path,
    include_ineligible=True,
)

comparison = (
    scores[
        scores["status"].eq("scored")
        & scores["variant_id"].isin(["full_system_fast", "raw_deepseek_v4_pro"])
    ]
    .pivot_table(
        index="metric_name",
        columns="variant_id",
        values="score",
        aggfunc="mean",
    )
    .reset_index()
)

if {"full_system_fast", "raw_deepseek_v4_pro"}.issubset(comparison.columns):
    comparison["delta_system_minus_raw_pro"] = (
        comparison["full_system_fast"] - comparison["raw_deepseek_v4_pro"]
    )

display(comparison)

print("Scored existing generations from:", generations_path)
print("Metrics saved to:", scores_path)

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

variant_id,metric_name,full_system_fast,raw_deepseek_v4_pro,delta_system_minus_raw_pro
0,bertscore_f1,0.883872,0.857373,0.026499
1,bleu,0.133743,0.117523,0.016220
2,chrf,0.468267,0.430503,0.037764
3,corpus_bleu,0.133743,0.117523,0.016220
4,corpus_chrf,0.468267,0.430503,0.037764
5,corpus_ter,0.795796,0.816817,-0.021021
6,meteor,0.296997,0.258609,0.038388
7,rouge1,0.569966,0.537102,0.032863
8,rouge2,0.219178,0.223404,-0.004226
9,rougeL,0.341297,0.289753,0.051544
10,rougeLsum,0.341297,0.289753,0.051544
11,ter,0.795796,0.816817,-0.021021

Scored existing generations from: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/sportsett_basketball_4934_fast_compare_generations.jsonl
Metrics saved to: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/sportsett_basketball_4934_fast_reference_metrics_fixed.jsonl

In [2]:
# Reference metrics only. No DeepEval.
metrics_path = project_dir / f"evaluation/config/metrics_{dataset_id}_{example_id}_fast_reference_only.json"

metrics_config = {
    "experiment_id": f"{dataset_id}_{example_id}_fast_reference_only",
    "prepared_examples_path": str(examples_path),
    "generations_path": str(generations_path),
    "result_directory": str(project_dir / "evaluation/results"),
    "baseline_variant": "raw_deepseek_v4_flash",
    "bootstrap_resamples": 5000,
    "confidence_level": 0.95,
    "random_seed": 42,
    "reference_metrics": {
        "enabled_metrics": [
            "bleu",
            "chrf",
            "ter",
            "rouge1",
            "rouge2",
            "rougeL",
            "rougeLsum",
            "meteor",
            "bertscore",
            "parent",
        ],
        "bertscore_model": "roberta-base",
        "bertscore_num_layers": None,
        "bertscore_batch_size": 8,
        "bertscore_device": None,
        "bertscore_rescale_with_baseline": False,
        "parent_n_jobs": 1,
        "hf_local_files_only": True,
        "external_factuality_context": "references",
        "lowercase": False,
    },
    "deepeval": {
        "enabled": False,
        "judge_provider": "deepseek",
        "judge_model": "deepseek-v4-pro",
        "judge_repetitions": 1,
        "threshold": 0.5,
        "max_source_characters": 50000,
        "run_summarization": False,
        "run_faithfulness": False,
        "run_factual_correctness": False,
        "run_reference_adequacy": False,
        "run_task_relevance": False,
        "run_coherence": False,
        "run_usefulness": False,
    },
}

metrics_path.write_text(json.dumps(metrics_config, indent=2), encoding="utf-8")

print("\nScoring reference metrics...")
scores_path = project_dir / f"evaluation/results/{dataset_id}_{example_id}_fast_reference_metrics.jsonl"

scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=generations_path,
    metric_config_path=metrics_path,
    output_path=scores_path,
)

comparison = (
    scores[
        scores["status"].eq("scored")
        & scores["variant_id"].isin(["full_system_fast", "raw_deepseek_v4_flash"])
    ]
    .pivot_table(
        index="metric_name",
        columns="variant_id",
        values="score",
        aggfunc="mean",
    )
    .reset_index()
)

if {"full_system_fast", "raw_deepseek_v4_flash"}.issubset(comparison.columns):
    comparison["delta_system_minus_raw"] = (
        comparison["full_system_fast"] - comparison["raw_deepseek_v4_flash"]
    )

display(comparison)

print("Metrics saved to:", scores_path)

Scoring reference metrics...

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

variant_id   metric_name  full_system_fast
0           bertscore_f1          0.853892
1                   bleu          0.113543
2                   chrf          0.436925
3            corpus_bleu          0.113543
4            corpus_chrf          0.436925
5             corpus_ter          0.879880
6                 meteor          0.280246
7                 rouge1          0.516640
8                 rouge2          0.162162
9                 rougeL          0.237718
10             rougeLsum          0.237718
11                   ter          0.879880

Metrics saved to: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/sportsett_basketball_4934_fast_reference_metrics.jsonl

In [3]:
import json
import os
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    load_project_env,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)
load_project_env(project_dir)

dataset_id = "sportsett_basketball"
example_id = "4934"

examples = read_examples(paths["prepared_examples"])
one_example = next(
    e for e in examples
    if e.dataset_id == dataset_id and str(e.example_id) == example_id
)

examples_path = project_dir / f"evaluation/prepared/{dataset_id}_{example_id}_raw_only.jsonl"
write_jsonl(examples_path, [one_example])

variants = {
    "variants": [
        {
            "variant_id": "raw_deepseek_v4_flash",
            "enabled": True,
            "backend": "callable",
            "description": "Raw one-shot DeepSeek flash baseline.",
            "settings_overrides": {
                "raw_baseline_model": "deepseek-v4-flash",
                "raw_baseline_max_source_characters": 100000,
                "raw_baseline_max_output_tokens": 1500,
                "raw_baseline_temperature": 0.2,
            },
            "callable_path": "table2text.evaluation_backends.single_agent_baseline",
            "command": [],
            "precomputed_path": None,
            "repetitions": 1,
            "seeds": [42],
        }
    ]
}

variants_path = project_dir / f"evaluation/config/variants_{dataset_id}_{example_id}_raw_only.json"
variants_path.write_text(json.dumps(variants, indent=2), encoding="utf-8")

generations_path = project_dir / f"evaluation/generations/{dataset_id}_{example_id}_raw_only_generations.jsonl"
run_root = project_dir / f"evaluation/generations/{dataset_id}_{example_id}_raw_only_runs"

print("Raw model:", variants["variants"][0]["settings_overrides"]["raw_baseline_model"])
print("Running raw baseline...")

raw_generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=generations_path,
    run_root=run_root,
    resume=False,
)

row = raw_generations.iloc[0]

print("\nDone.")
print("Variant:", row["variant_id"])
print("Error:", row["error"])
print("Elapsed seconds:", row["elapsed_seconds"])

print("\nGenerated text:\n")
print(row["generated_text"])

raw_generations[
    [
        "dataset_id",
        "example_id",
        "variant_id",
        "generated_text",
        "error",
        "elapsed_seconds",
    ]
]

Raw model: deepseek-v4-flash
Running raw baseline...

Done.
Variant: raw_deepseek_v4_flash
Error: None
Elapsed seconds: 17.01298483402934

Generated text:

The Philadelphia 76ers defeated the Memphis Grizzlies 103-95 on Sunday, December 2, 2018, at Wells Fargo Center in Philadelphia. The 76ers improved to 17-8, while the Grizzlies dropped to 13-9. Philadelphia led 54-44 at halftime and carried a 78-68 advantage into the fourth quarter before closing out the win in front of 20,300 fans.

J.J. Redick led the 76ers with 24 points, shooting 9-of-17 from the field and 3-of-6 from three-point range. Jimmy Butler added 21 points and went 7-of-8 from the free-throw line. Ben Simmons posted a double-double with 19 points, 12 rebounds, and 6 assists, while Joel Embiid also recorded a double-double with 15 points and 14 rebounds. Philadelphia shot 49 percent from the field and converted 23 of 30 free throws.

Mike Conley paced Memphis with 21 points on 6-of-17 shooting and added 5 assists. Jaren Jackson Jr. scored 17 points and blocked 3 shots, and JaMychal Green contributed 14 points and 7 rebounds off the bench. Marc Gasol had 12 points and 2 blocks.

The 76ers controlled the rebounding battle 44-35 and made more free throws, while the Grizzlies hit 11 three-pointers and blocked 7 shots. Memphis outscored Philadelphia 27-25 in the final quarter, but the 76ers’ balanced offense and strong first-half margin proved decisive.

,dataset_id,example_id,variant_id,generated_text,error,elapsed_seconds
0,sportsett_basketball,4934,raw_deepseek_v4_flash,The Philadelphia 76ers defeated the Memphis Gr...,None,17.012985

In [4]:
import json
from pathlib import Path

from table2text.evaluation import score_reference_metrics_for_notebook

def read_jsonl_file(path):
    rows = []
    with Path(path).open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows

def write_jsonl_file(path, rows):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")

full_system_path = project_dir / "evaluation/generations/sportsett_basketball_4934_fast_compare_generations.jsonl"
raw_path = project_dir / "evaluation/generations/sportsett_basketball_4934_raw_only_generations.jsonl"

full_rows = [
    row for row in read_jsonl_file(full_system_path)
    if row.get("variant_id") == "full_system_fast"
]

raw_rows = [
    row for row in read_jsonl_file(raw_path)
    if row.get("variant_id") == "raw_deepseek_v4_flash"
]

print("Full-system rows:", len(full_rows))
print("Raw rows:", len(raw_rows))

combined_path = project_dir / "evaluation/generations/sportsett_basketball_4934_fast_vs_raw_generations.jsonl"
write_jsonl_file(combined_path, [*full_rows, *raw_rows])

metrics_path = project_dir / "evaluation/config/metrics_sportsett_basketball_4934_fast_vs_raw_reference_only.json"

metrics_config = {
    "experiment_id": "sportsett_basketball_4934_fast_vs_raw_reference_only",
    "prepared_examples_path": str(project_dir / "evaluation/prepared/sportsett_basketball_4934_raw_only.jsonl"),
    "generations_path": str(combined_path),
    "result_directory": str(project_dir / "evaluation/results"),
    "baseline_variant": "raw_deepseek_v4_flash",
    "bootstrap_resamples": 5000,
    "confidence_level": 0.95,
    "random_seed": 42,
    "reference_metrics": {
        "enabled_metrics": [
            "bleu",
            "chrf",
            "ter",
            "rouge1",
            "rouge2",
            "rougeL",
            "rougeLsum",
            "meteor",
            "bertscore",
            "parent",
        ],
        "bertscore_model": "roberta-base",
        "bertscore_num_layers": None,
        "bertscore_batch_size": 8,
        "bertscore_device": None,
        "bertscore_rescale_with_baseline": False,
        "parent_n_jobs": 1,
        "hf_local_files_only": True,
        "external_factuality_context": "references",
        "lowercase": False,
    },
    "deepeval": {
        "enabled": False,
        "judge_provider": "deepseek",
        "judge_model": "deepseek-v4-pro",
        "judge_repetitions": 1,
        "threshold": 0.5,
        "max_source_characters": 50000,
        "run_summarization": False,
        "run_faithfulness": False,
        "run_factual_correctness": False,
        "run_reference_adequacy": False,
        "run_task_relevance": False,
        "run_coherence": False,
        "run_usefulness": False,
    },
}

metrics_path.write_text(json.dumps(metrics_config, indent=2), encoding="utf-8")

scores_path = project_dir / "evaluation/results/sportsett_basketball_4934_fast_vs_raw_reference_metrics.jsonl"

scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=combined_path,
    metric_config_path=metrics_path,
    output_path=scores_path,
)

comparison = (
    scores[scores["status"].eq("scored")]
    .pivot_table(
        index="metric_name",
        columns="variant_id",
        values="score",
        aggfunc="mean",
    )
    .reset_index()
)

if {"full_system_fast", "raw_deepseek_v4_flash"}.issubset(comparison.columns):
    comparison["delta_system_minus_raw"] = (
        comparison["full_system_fast"] - comparison["raw_deepseek_v4_flash"]
    )

display(comparison)

print("Combined generations:", combined_path)
print("Metrics:", scores_path)

Full-system rows: 1
Raw rows: 1

Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

variant_id,metric_name,full_system_fast,raw_deepseek_v4_flash,delta_system_minus_raw
0,bertscore_f1,0.853892,0.859633,-0.005741
1,bleu,0.113543,0.125477,-0.011934
2,chrf,0.436925,0.392048,0.044877
3,corpus_bleu,0.113543,0.125477,-0.011934
4,corpus_chrf,0.436925,0.392048,0.044877
5,corpus_ter,0.879880,0.807808,0.072072
6,meteor,0.280246,0.246464,0.033782
7,rouge1,0.516640,0.490494,0.026146
8,rouge2,0.162162,0.209924,-0.047762
9,rougeL,0.237718,0.315589,-0.077871
10,rougeLsum,0.237718,0.315589,-0.077871
11,ter,0.879880,0.807808,0.072072

Combined generations: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/sportsett_basketball_4934_fast_vs_raw_generations.jsonl
Metrics: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/sportsett_basketball_4934_fast_vs_raw_reference_metrics.jsonl

In [2]:
import json
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)

# Same five examples we have been using
TARGETS = [
    ("sportsett_basketball", "4934"),
    ("e2e_nlg", "e2e_nlg-test-51"),
    ("totto", "totto-validation-204"),
    ("web_nlg", "web_nlg_en-test-51"),
    ("dart", "dart-test-53"),
]

examples = read_examples(paths["prepared_examples"])
selected = []

for dataset_id, example_id in TARGETS:
    match = next(
        e for e in examples
        if e.dataset_id == dataset_id and e.example_id == example_id
    )
    selected.append(match)

examples_path = project_dir / "evaluation/prepared/five_dataset_writer_gpt55_examples.jsonl"
write_jsonl(examples_path, selected)

variant = {
    "variants": [
        {
            "variant_id": "full_system_flash_pipeline_gpt55_writer",
            "enabled": True,
            "backend": "table2text",
            "description": "DeepSeek flash/basic pipeline with OpenAI GPT-5.5 writer.",
            "settings_overrides": {
                "use_llm": True,
                "structured_output_mode": "prompted",
                "max_total_tokens": 80000,
                "max_agent_requests": 8,

                "force_llm_short_form_writer": False,

                "data_understanding_model": "deepseek:deepseek-v4-flash",
                "orchestrator_model": "deepseek:deepseek-v4-flash",
                "evidence_model": "deepseek:deepseek-v4-flash",
                "verifier_model": "deepseek:deepseek-v4-flash",
                "writer_model": "openai:gpt-5.5",
                "auditor_model": "deepseek:deepseek-v4-flash",
            },
            "callable_path": None,
            "command": [],
            "precomputed_path": None,
            "repetitions": 1,
            "seeds": [42],
        }
    ]
}

variants_path = project_dir / "evaluation/config/variants_five_dataset_flash_pipeline_gpt55_writer.json"
variants_path.parent.mkdir(parents=True, exist_ok=True)
variants_path.write_text(json.dumps(variant, indent=2), encoding="utf-8")

generations_path = project_dir / "evaluation/generations/five_dataset_flash_pipeline_gpt55_writer_generations.jsonl"
run_root = project_dir / "evaluation/generations/five_dataset_flash_pipeline_gpt55_writer_runs"

generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=generations_path,
    run_root=run_root,
    resume=False,
)

display(
    generations[
        [
            "dataset_id",
            "example_id",
            "variant_id",
            "generated_text",
            "error",
            "release_status",
            "writer_mode",
            "elapsed_seconds",
        ]
    ]
)

# Reference metrics, no DeepEval here
scores_path = project_dir / "evaluation/results/five_dataset_flash_pipeline_gpt55_writer_reference_metrics.jsonl"

scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=generations_path,
    metric_config_path=paths["metric_config"],
    output_path=scores_path,
    include_ineligible=True,
)

metric_table = (
    scores[scores["status"].eq("scored")]
    .pivot_table(
        index=["dataset_id", "example_id", "metric_name"],
        columns="variant_id",
        values="score",
        aggfunc="first",
    )
    .reset_index()
)

display(metric_table)

print("Examples:", examples_path)
print("Variants:", variants_path)
print("Generations:", generations_path)
print("Run root:", run_root)
print("Scores:", scores_path)

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/pydantic_ai/agent/__init__.py:415: PydanticAIDeprecationWarning: In v2.0, 'openai:' will resolve to the OpenAI Responses API by default. Use 'openai-chat:' to keep current Chat Completions behavior, or 'openai-responses:' to opt in early.
  self._model = models.infer_model(model)
/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/pydantic_ai/agent/__init__.py:415: PydanticAIDeprecationWarning: In v2.0, 'openai:' will resolve to the OpenAI Responses API by default. Use 'openai-chat:' to keep current Chat Completions behavior, or 'openai-responses:' to opt in early.
  self._model = models.infer_model(model)
/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/pydantic_ai/agent/__init__.py:415: PydanticAIDeprecationWarning: In v2.0, 'openai:' will resolve to the OpenAI Responses API by default. Use 'openai-chat:' to keep current Chat Completions behavior, or 'openai-responses:' to opt in early.
  self._model = models.infer_model(model)
/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/pydantic_ai/agent/__init__.py:415: PydanticAIDeprecationWarning: In v2.0, 'openai:' will resolve to the OpenAI Responses API by default. Use 'openai-chat:' to keep current Chat Completions behavior, or 'openai-responses:' to opt in early.
  self._model = models.infer_model(model)
/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/pydantic_ai/agent/__init__.py:415: PydanticAIDeprecationWarning: In v2.0, 'openai:' will resolve to the OpenAI Responses API by default. Use 'openai-chat:' to keep current Chat Completions behavior, or 'openai-responses:' to opt in early.
  self._model = models.infer_model(model)

,dataset_id,example_id,variant_id,generated_text,error,release_status,writer_mode,elapsed_seconds
0,dart,dart-test-53,full_system_flash_pipeline_gpt55_writer,University of Makati UM Pep Squad has a total ...,None,approved_with_warnings,llm_writer,4.612147
1,e2e_nlg,e2e_nlg-test-51,full_system_flash_pipeline_gpt55_writer,Clowns is a pub near Crowne Plaza Hotel with a...,None,approved_with_warnings,llm_writer,4.703231
2,sportsett_basketball,4934,full_system_flash_pipeline_gpt55_writer,The Philadelphia 76ers beat the Memphis Grizzl...,None,approved,llm_writer,870.944488
3,totto,totto-validation-204,full_system_flash_pipeline_gpt55_writer,Ma Ying-jeou received 58.45% of the vote.\n,None,approved_with_warnings,llm_writer,7.786601
4,web_nlg,web_nlg_en-test-51,full_system_flash_pipeline_gpt55_writer,"ALCO_RS-3's engine is Four-stroke_engine, it h...",None,approved_with_warnings,llm_writer,9.193473

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
You are using a model of type HHEMv2Config to instantiate a model of type HHEMv2. This is not supported for all configurations of models and can yield errors.
Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

variant_id,dataset_id,example_id,metric_name,full_system_flash_pipeline_gpt55_writer
0,dart,dart-test-53,alignscore_base,0.394325
1,dart,dart-test-53,bertscore_f1,0.926383
2,dart,dart-test-53,bleu,0.195648
3,dart,dart-test-53,chrf,0.566182
4,dart,dart-test-53,corpus_bleu,0.195648
...,...,...,...,...
75,web_nlg,web_nlg_en-test-51,rouge1,0.717949
76,web_nlg,web_nlg_en-test-51,rouge2,0.451613
77,web_nlg,web_nlg_en-test-51,rougeL,0.615385
78,web_nlg,web_nlg_en-test-51,rougeLsum,0.615385
79,web_nlg,web_nlg_en-test-51,ter,0.800000

Examples: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/prepared/five_dataset_writer_gpt55_examples.jsonl
Variants: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/config/variants_five_dataset_flash_pipeline_gpt55_writer.json
Generations: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/five_dataset_flash_pipeline_gpt55_writer_generations.jsonl
Run root: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/five_dataset_flash_pipeline_gpt55_writer_runs
Scores: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/five_dataset_flash_pipeline_gpt55_writer_reference_metrics.jsonl

In [1]:
import json
from pathlib import Path

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
variant_path = project_dir / "evaluation/config/variants_full_system_openai_gpt55_same_as_pro.json"

payload = json.loads(variant_path.read_text(encoding="utf-8"))
payload["variants"][0]["settings_overrides"]["force_llm_short_form_writer"]

False

In [1]:
import json
import time
from datetime import datetime
from pathlib import Path

from table2text.evaluation import (
    default_paths,
    generate_reports_for_notebook,
    score_reference_metrics_for_notebook,
    load_project_env,
)
from table2text.evaluation.datasets import read_examples, write_jsonl

project_dir = Path("/Users/realgobs/Documents/MScproject/table2text_pydanticai")
paths = default_paths(project_dir)
load_project_env(project_dir)

dataset_id = "sportsett_basketball"
example_id = "4934"

# Change this if you want pro.
MODEL = "deepseek-v4-flash"
# MODEL = "deepseek-v4-pro"

run_tag = datetime.now().strftime("%Y%m%d_%H%M%S")
experiment_name = f"{dataset_id}_{example_id}_inferred_contract_{MODEL}_{run_tag}"

examples = read_examples(paths["prepared_examples"])
one_example = next(
    e for e in examples
    if e.dataset_id == dataset_id and str(e.example_id) == example_id
)

examples_path = project_dir / f"evaluation/prepared/{experiment_name}.jsonl"
write_jsonl(examples_path, [one_example])

variants_payload = json.loads(paths["variant_config"].read_text(encoding="utf-8"))
base_variant = next(
    variant for variant in variants_payload["variants"]
    if variant["variant_id"] == "full_inferred_contract"
)

variant = {
    **base_variant,
    "enabled": True,
    "variant_id": f"full_inferred_contract_{MODEL.replace('-', '_')}",
    "settings_overrides": {
        **base_variant.get("settings_overrides", {}),
        "data_understanding_model": f"deepseek:{MODEL}",
        "orchestrator_model": f"deepseek:{MODEL}",
        "evidence_model": f"deepseek:{MODEL}",
        "verifier_model": f"deepseek:{MODEL}",
        "writer_model": f"deepseek:{MODEL}",
        "auditor_model": f"deepseek:{MODEL}",
        "max_total_tokens": 300000,
        "max_agent_requests": 8,
    },
}

variants_path = project_dir / f"evaluation/config/variants_{experiment_name}.json"
variants_path.write_text(json.dumps({"variants": [variant]}, indent=2), encoding="utf-8")

generations_path = project_dir / f"evaluation/generations/{experiment_name}_generations.jsonl"
run_root = project_dir / f"evaluation/generations/{experiment_name}_runs"

print("Experiment:", experiment_name)
print("Workflow model:", MODEL)
print("Variant:", variant["variant_id"])
print("Running inferred-contract workflow...")

t0 = time.perf_counter()

generations = await generate_reports_for_notebook(
    project_dir,
    examples_path=examples_path,
    variants_path=variants_path,
    output_path=generations_path,
    run_root=run_root,
    resume=False,
)

print(f"\nGeneration finished in {time.perf_counter() - t0:.1f}s")

row = generations.iloc[0]
metadata = row.get("metadata") or {}

print("\nDone.")
print("Variant:", row["variant_id"])
print("Error:", row["error"])
print("Release status:", row.get("release_status"))
print("Writer mode:", row.get("writer_mode"))
print("Elapsed seconds:", row["elapsed_seconds"])
print("Pipeline result:", row.get("pipeline_result_path"))

print("\nInferred contract:")
print(json.dumps(metadata.get("inferred_task_contract"), indent=2))

print("\nResolved contract:")
print(json.dumps(metadata.get("resolved_task_contract"), indent=2))

print("\nAgreement:")
print(json.dumps(metadata.get("task_contract_agreement"), indent=2))

print("\nGenerated text:\n")
print(row["generated_text"])

display(
    generations[
        [
            "dataset_id",
            "example_id",
            "variant_id",
            "generated_text",
            "error",
            "release_status",
            "writer_mode",
            "elapsed_seconds",
        ]
    ]
)

# =========================
# Compare metrics with saved full_system/raw_generic_flash rows
# =========================

saved_generations_path = (
    project_dir
    / "evaluation/generations/five_dataset_five_each_raw_generic_flash_20260805_181001_combined_generations.jsonl"
)

saved_rows = []
if saved_generations_path.exists():
    for line in saved_generations_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        saved_row = json.loads(line)
        if (
            saved_row.get("dataset_id") == dataset_id
            and str(saved_row.get("example_id")) == example_id
            and saved_row.get("variant_id") in {"full_system", "raw_generic_flash"}
        ):
            saved_rows.append(saved_row)

new_row = row.to_dict()

combined_generations_path = (
    project_dir
    / f"evaluation/generations/{experiment_name}_vs_saved_generations.jsonl"
)

with combined_generations_path.open("w", encoding="utf-8") as handle:
    for item in [*saved_rows, new_row]:
        handle.write(json.dumps(item, ensure_ascii=False) + "\n")

print("\nSaved comparison rows found:", len(saved_rows))
print("Combined generations:", combined_generations_path)

base_metrics_path = (
    project_dir
    / "evaluation/config/metrics_five_dataset_five_each_raw_generic_flash_20260805_181001_reference.json"
)

metrics_payload = json.loads(base_metrics_path.read_text(encoding="utf-8"))
metrics_payload = {
    **metrics_payload,
    "experiment_id": experiment_name,
    "prepared_examples_path": str(examples_path),
    "generations_path": str(combined_generations_path),
    "baseline_variant": "raw_generic_flash",
}

metrics_path = project_dir / f"evaluation/config/metrics_{experiment_name}_reference.json"
metrics_path.write_text(json.dumps(metrics_payload, indent=2), encoding="utf-8")

scores_path = project_dir / f"evaluation/results/{experiment_name}_reference_metrics.jsonl"

print("\nScoring reference metrics...")
t0 = time.perf_counter()

scores = score_reference_metrics_for_notebook(
    project_dir,
    generations_path=combined_generations_path,
    metric_config_path=metrics_path,
    output_path=scores_path,
    include_ineligible=True,
)

print(f"Metrics finished in {time.perf_counter() - t0:.1f}s")
print("Metrics output:", scores_path)

metric_table = (
    scores[scores["status"].isin(["scored", "error", "skipped", "unavailable"])]
    .pivot_table(
        index=["dataset_id", "example_id", "metric_name"],
        columns="variant_id",
        values="score",
        aggfunc="first",
    )
    .reset_index()
)

display(metric_table)

Experiment: sportsett_basketball_4934_inferred_contract_deepseek-v4-flash_20260813_203625
Workflow model: deepseek-v4-flash
Variant: full_inferred_contract_deepseek_v4_flash
Running inferred-contract workflow...

Generation finished in 946.3s

Done.
Variant: full_inferred_contract_deepseek_v4_flash
Error: None
Release status: approved_with_warnings
Writer mode: auditor_repaired
Elapsed seconds: 946.2467942920048
Pipeline result: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/sportsett_basketball_4934_inferred_contract_deepseek-v4-flash_20260813_203625_runs/full_inferred_contract_deepseek_v4_flash/sportsett_basketball/20260813T193626Z_20134e6d5b/pipeline_result.json

Inferred contract:
{
  "task_family": "event_report",
  "report_genre": "sports_game_report",
  "communication_task": "event_report",
  "output_form": "multi_paragraph_report",
  "focus_scope": "Single-game recap with home and visiting team totals and notable player performances",
  "selection_source": "structured_inference",
  "confidence": 0.98,
  "evidence": [
    "The input-structure profile identifies one bounded event record."
  ],
  "unresolved_ambiguities": []
}

Resolved contract:
{
  "task_family": "event_report",
  "report_genre": "sports_game_report",
  "communication_task": "event_report",
  "output_form": "multi_paragraph_report",
  "focus_scope": "Single-game recap with home and visiting team totals and notable player performances",
  "selection_source": "structured_inference",
  "confidence": 0.98,
  "evidence": [
    "The input-structure profile identifies one bounded event record."
  ],
  "unresolved_ambiguities": []
}

Agreement:
{
  "fields": {
    "task_family": true,
    "report_genre": true,
    "communication_task": true,
    "output_form": true,
    "focus_scope": true
  },
  "exact_match": true,
  "inferred_confidence": 0.98,
  "inferred_source": "structured_inference",
  "resolved_source": "structured_inference"
}

Generated text:

# 76ers edge Grizzlies 103-95 at Wells Fargo Center

## Event overview

On Sunday, December 2, 2018, at Wells Fargo Center, the Philadelphia 76ers defeated the Memphis Grizzlies 103-95 in the 2018 season.
Philadelphia entered the game with 17 wins and 8 losses, while Memphis entered with 13 wins and 9 losses; the contest was the 76ers' 25th game and the Grizzlies' 22nd.

## Score progression

Philadelphia led after every recorded quarter, holding a 26-25 edge after Q1, 54-44 after Q2, 78-68 after Q3, and 103-95 after Q4.
The teams recorded an even 24-24 third quarter before Philadelphia's cumulative lead reached 78-68.

## Key performances

J.J. Redick led all players with 24 points and 9 field goals made.
Joel Embiid led all players with 14 total rebounds and 14 defensive rebounds, while Ben Simmons ranked second in both categories with 12 total and 10 defensive rebounds and also led all players with 6 assists.
The top four plus-minus marks all belonged to 76ers players: T.J. McConnell at +16, Joel Embiid at +13, J.J. Redick at +9, and Jimmy Butler at +7.
For Memphis, JaMychal Green led all players with 4 steals and Jaren Jackson led all players with 3 blocks.
Mike Muscala and Furkan Korkmaz of the 76ers tied for the highest recorded three-point percentage at 67.

## Participant contrasts

Philadelphia recorded team advantages in total rebounds (44-35), defensive rebounds (41-32), field goals made (36-33), free throws made (23-18), and free throws attempted (30-23).
Memphis, meanwhile, recorded higher totals in field-goal attempts (79-74), three-point attempts (28-22), and three-pointers made (11-8).
Philadelphia shot 49 percent from the field, compared with 42 percent for Memphis.

## Scope limitations

These comparisons describe only the supplied event: the single-game package records event context, final score, quarter scores, box-score rankings, and the teams' entering records, but does not include season standings or causal explanations.

,dataset_id,example_id,variant_id,generated_text,error,release_status,writer_mode,elapsed_seconds
0,sportsett_basketball,4934,full_inferred_contract_deepseek_v4_flash,# 76ers edge Grizzlies 103-95 at Wells Fargo C...,None,approved_with_warnings,auditor_repaired,946.246794

Saved comparison rows found: 2
Combined generations: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/generations/sportsett_basketball_4934_inferred_contract_deepseek-v4-flash_20260813_203625_vs_saved_generations.jsonl

Scoring reference metrics...

/Users/realgobs/Documents/MScproject/table2text_pydanticai/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
You are using a model of type HHEMv2Config to instantiate a model of type HHEMv2. This is not supported for all configurations of models and can yield errors.
Some weights of RobertaModel were not initialized from the model checkpoint at /Users/realgobs/.cache/huggingface/hub/models--roberta-base/snapshots/e2da8e2f811d1448a5b465c236feacd80ffbac7b and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Metrics finished in 67.8s
Metrics output: /Users/realgobs/Documents/MScproject/table2text_pydanticai/evaluation/results/sportsett_basketball_4934_inferred_contract_deepseek-v4-flash_20260813_203625_reference_metrics.jsonl

variant_id,dataset_id,example_id,metric_name,full_inferred_contract_deepseek_v4_flash,full_system,raw_generic_flash
0,sportsett_basketball,4934,alignscore_base,0.248494,0.287307,0.389757
1,sportsett_basketball,4934,bertscore_f1,0.831492,0.867145,0.814384
2,sportsett_basketball,4934,bleu,0.075389,0.123164,0.030178
3,sportsett_basketball,4934,chrf,0.372448,0.443245,0.224788
4,sportsett_basketball,4934,corpus_bleu,0.075389,0.123164,0.030178
5,sportsett_basketball,4934,corpus_chrf,0.372448,0.443245,0.224788
6,sportsett_basketball,4934,corpus_ter,0.864865,0.843844,0.810811
7,sportsett_basketball,4934,hhem_2_1_open_mean_support,0.101822,0.196381,0.142276
8,sportsett_basketball,4934,hhem_2_1_open_min_sentence_support,0.007466,0.011010,0.057770
9,sportsett_basketball,4934,hhem_2_1_open_unsupported_sentence_rate,1.000000,0.833333,1.000000
10,sportsett_basketball,4934,meteor,0.217022,0.258795,0.167685
11,sportsett_basketball,4934,rouge1,0.403846,0.518639,0.356627
12,sportsett_basketball,4934,rouge2,0.109325,0.204878,0.145278
13,sportsett_basketball,4934,rougeL,0.201923,0.275527,0.240964
14,sportsett_basketball,4934,rougeLsum,0.201923,0.275527,0.240964
15,sportsett_basketball,4934,ter,0.864865,0.843844,0.810811